import { DEFAULT_PLATES } from "./plates";
import type { EquipmentId, EquipmentProfile, Exercise, Muscle, TargetMuscle } from "./types";

export const EQUIPMENT: { id: EquipmentId; label: string }[] = [
  { id: "bodyweight", label: "Bodyweight" },
  { id: "barbell", label: "Barbells" },
  { id: "dumbbell", label: "Dumbbells" },
  { id: "cable", label: "Low / Mid Cable" },
  { id: "cable_high", label: "High Cable Pulley (Lat Station)" },
  { id: "smith", label: "Smith Machine (Guided Barbell)" },
  { id: "bench", label: "Adjustable Bench (Flat / Incline / Decline)" },
  { id: "leg_developer", label: "Leg Developer (Extension & Lying Curl)" },
  { id: "bands", label: "Resistance Bands" },
  { id: "kettlebell", label: "Kettlebells" },
  { id: "pullup_bar", label: "Pull-up Bar" },
  { id: "dip_bars", label: "Dip Bars / Parallel Bars" },
  { id: "leg_press", label: "Leg Press" },
  { id: "machine", label: "Pin-Loaded Machines" },
];

export const MUSCLES: Muscle[] = [
  "Chest",
  "Back",
  "Shoulders",
  "Arms",
  "Quads",
  "Hamstrings",
  "Glutes",
  "Core",
  "Calves",
];

const baseProfile = () => ({
  plates: { ...DEFAULT_PLATES },
  bar_weight: 20,
  dumbbell_bar_weight: 2,
});

export const DEFAULT_PROFILES: EquipmentProfile[] = (
  [
    {
      id: "full-gym",
      name: "Full Commercial Gym",
      active_equipment_ids: EQUIPMENT.map((e) => e.id),
    },
    {
      id: "home-gym",
      name: "Home Gym",
      active_equipment_ids: [
        "bodyweight",
        "dumbbell",
        "barbell",
        "smith",
        "cable_high",
        "bench",
        "leg_developer",
      ],
    },
    {
      id: "hotel-gym",
      name: "Hotel / Travel",
      active_equipment_ids: ["bodyweight", "dumbbell", "bench", "machine", "bands"],
    },
    {
      id: "home-db",
      name: "Home Dumbbells Only",
      active_equipment_ids: ["bodyweight", "dumbbell", "bench"],
    },
    {
      id: "bands-bodyweight",
      name: "Bands & Bodyweight",
      active_equipment_ids: ["bodyweight", "bands", "pullup_bar"],
    },
    {
      id: "bodyweight",
      name: "Bodyweight",
      active_equipment_ids: ["bodyweight", "pullup_bar"],
    },
  ] as Omit<EquipmentProfile, "plates" | "bar_weight" | "dumbbell_bar_weight">[]
).map((p) => ({ ...p, ...baseProfile() }));

export const EXERCISES: Exercise[] = [
  {
    id: "bb-bench",
    name: "Barbell Bench Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Shoulders", "Arms"],
    muscle_targets: ["Mid Chest", "Triceps", "Front Delts"],
    equipment_required: ["barbell", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions: "Press the bar from mid-chest to lockout with a stable arch and planted feet.",
    cues: [
      "Keep elbows tucked at 45 degrees",
      "Squeeze shoulder blades down and back",
      "Bar path in a slight arc toward the eyes",
    ],
  },
  {
    id: "db-bench",
    name: "Dumbbell Bench Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Shoulders", "Arms"],
    muscle_targets: ["Mid Chest", "Triceps", "Front Delts"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions: "Press dumbbells from chest level until they nearly touch overhead.",
    cues: ["Wrists stacked over elbows", "Control the eccentric for 2 seconds"],
  },
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Shoulders"],
    muscle_targets: ["Upper Chest", "Front Delts", "Triceps"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions: "Bench at 30 degrees, press dumbbells up and slightly together.",
    cues: ["Don't flare elbows past 60 degrees", "Stop 1 inch short of lockout"],
  },
  {
    id: "cable-crossover",
    name: "Cable Crossover",
    primary_muscle: "Chest",
    secondary_muscles: [],
    muscle_targets: ["Mid Chest", "Lower Chest"],
    equipment_required: ["cable"],
    movement_pattern: "push",
    compound: false,
    instructions: "Sweep handles together in front of the sternum with a soft elbow bend.",
    cues: ["Lead with the elbows, not the hands", "Pause 1s at peak contraction"],
  },
  {
    id: "db-fly",
    name: "Dumbbell Flye",
    primary_muscle: "Chest",
    secondary_muscles: [],
    muscle_targets: ["Mid Chest"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "push",
    compound: false,
    instructions: "Open the arms wide in an arc, then hug back to the top.",
    cues: ["Fixed elbow angle throughout", "Stretch, don't drop"],
  },
  {
    id: "band-fly",
    name: "Resistance Band Flye",
    primary_muscle: "Chest",
    secondary_muscles: [],
    muscle_targets: ["Mid Chest"],
    equipment_required: ["bands"],
    movement_pattern: "push",
    compound: false,
    instructions: "Anchor bands behind you and press the hands together at chest height.",
    cues: ["Keep tension at the start position", "Ribs down"],
  },
  {
    id: "pushup",
    name: "Push-Up",
    primary_muscle: "Chest",
    secondary_muscles: ["Core", "Arms"],
    muscle_targets: ["Mid Chest", "Triceps", "Front Delts"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: true,
    instructions: "Lower the chest to the floor keeping a straight line head to heel.",
    cues: ["Squeeze glutes to lock the ribcage", "Elbows at 45 degrees"],
  },
  {
    id: "pullup",
    name: "Pull-Up",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Biceps"],
    equipment_required: ["pullup_bar"],
    movement_pattern: "pull",
    compound: true,
    instructions: "Pull the chest toward the bar from a dead hang.",
    cues: ["Start each rep from full hang", "Drive elbows down to the pockets"],
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Biceps"],
    equipment_required: ["cable_high"],
    movement_pattern: "pull",
    compound: true,
    instructions: "Pull the bar to the upper chest with a slight torso lean.",
    cues: ["Chest up, no swinging", "Think elbows to hips"],
  },
  {
    id: "bb-row",
    name: "Barbell Bent-Over Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms", "Hamstrings"],
    muscle_targets: ["Lats", "Traps", "Biceps"],
    equipment_required: ["barbell"],
    movement_pattern: "pull",
    compound: true,
    instructions: "Hinge to 45 degrees and row the bar to the lower ribs.",
    cues: ["Neutral spine, brace hard", "Pull to the belly button"],
  },
  {
    id: "db-row",
    name: "One-Arm Dumbbell Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Traps", "Biceps"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "pull",
    compound: true,
    instructions: "Support on a bench and row the dumbbell to the hip.",
    cues: ["Don't rotate the torso", "Full stretch at the bottom"],
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Traps", "Biceps"],
    equipment_required: ["cable"],
    movement_pattern: "pull",
    compound: true,
    instructions: "Row the handle to the navel, keeping the torso upright.",
    cues: ["Shoulders down away from ears", "Pause 1s at the squeeze"],
  },
  {
    id: "band-row",
    name: "Resistance Band Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Traps", "Biceps"],
    equipment_required: ["bands"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Anchor the band at chest height and row the handles to the ribs.",
    cues: ["Squeeze the mid-back", "Slow return"],
  },
  {
    id: "inverted-row",
    name: "Inverted Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms", "Core"],
    muscle_targets: ["Lats", "Traps", "Biceps"],
    equipment_required: ["bodyweight", "pullup_bar"],
    movement_pattern: "pull",
    compound: true,
    instructions: "Hang under a bar and pull the chest to it with a rigid body.",
    cues: ["Body in one straight line", "Chest touches the bar"],
  },
  {
    id: "ohp",
    name: "Standing Overhead Press",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Arms", "Core"],
    muscle_targets: ["Front Delts", "Side Delts", "Triceps"],
    equipment_required: ["barbell"],
    movement_pattern: "push",
    compound: true,
    instructions: "Press the bar overhead and finish with biceps by the ears.",
    cues: ["Squeeze glutes, no back lean", "Head through at lockout"],
  },
  {
    id: "db-shoulder-press",
    name: "Seated Dumbbell Shoulder Press",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Front Delts", "Side Delts", "Triceps"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions: "Press dumbbells from ear height to overhead.",
    cues: ["Elbows slightly in front of the body", "Ribs down"],
  },
  {
    id: "lateral-raise",
    name: "Dumbbell Lateral Raise",
    primary_muscle: "Shoulders",
    secondary_muscles: [],
    muscle_targets: ["Side Delts"],
    equipment_required: ["dumbbell"],
    movement_pattern: "push",
    compound: false,
    instructions: "Raise the dumbbells out to shoulder height with a soft elbow.",
    cues: ["Lead with the elbows", "No momentum — 2s down"],
  },
  {
    id: "cable-lateral",
    name: "Cable Lateral Raise",
    primary_muscle: "Shoulders",
    secondary_muscles: [],
    muscle_targets: ["Side Delts"],
    equipment_required: ["cable"],
    movement_pattern: "push",
    compound: false,
    instructions: "Raise the handle across the body out to the side.",
    cues: ["Constant tension at the bottom", "Stop at shoulder height"],
  },
  {
    id: "face-pull",
    name: "Cable Face Pull",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Back"],
    muscle_targets: ["Rear Delts", "Traps"],
    equipment_required: ["cable_high"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Pull the rope to the forehead, rotating the hands back.",
    cues: ["High elbows", "Externally rotate at the end range"],
  },
  {
    id: "bb-curl",
    name: "Barbell Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps", "Forearms"],
    equipment_required: ["barbell"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Curl the bar up without swinging the elbows forward.",
    cues: ["Elbows pinned to the ribs", "Control the negative"],
  },
  {
    id: "db-curl",
    name: "Dumbbell Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps", "Forearms"],
    equipment_required: ["dumbbell"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Curl and supinate the dumbbells one or both arms at a time.",
    cues: ["Turn the pinky up at the top", "No shoulder shrug"],
  },
  {
    id: "cable-pushdown",
    name: "Cable Triceps Pushdown",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Triceps"],
    equipment_required: ["cable_high"],
    movement_pattern: "push",
    compound: false,
    instructions: "Extend the elbows fully, keeping the upper arms still.",
    cues: ["Lock the elbows to your sides", "Full lockout squeeze"],
  },
  {
    id: "dips",
    name: "Parallel Bar Dip",
    primary_muscle: "Arms",
    secondary_muscles: ["Chest", "Shoulders"],
    muscle_targets: ["Triceps", "Lower Chest", "Front Delts"],
    equipment_required: ["bodyweight", "dip_bars"],
    movement_pattern: "push",
    compound: true,
    instructions: "Lower until the upper arms are parallel to the floor, then press up.",
    cues: ["Slight forward lean for chest", "Shoulders stay packed"],
  },
  {
    id: "skullcrusher",
    name: "Dumbbell Skullcrusher",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Triceps"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "push",
    compound: false,
    instructions: "Lower the dumbbells beside the head and extend back up.",
    cues: ["Elbows stay pointed at the ceiling", "Stretch behind the head"],
  },
  {
    id: "bb-squat",
    name: "Barbell Back Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes", "Core"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["barbell"],
    movement_pattern: "squat",
    compound: true,
    instructions: "Squat to at least parallel with the bar over mid-foot.",
    cues: ["Brace as if bracing for a punch", "Knees track over toes"],
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes", "Core"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["dumbbell"],
    movement_pattern: "squat",
    compound: true,
    instructions: "Hold a dumbbell at the chest and squat between the knees.",
    cues: ["Chest tall, elbows inside knees", "Sit down, not back"],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["leg_press"],
    movement_pattern: "squat",
    compound: true,
    instructions: "Lower the sled until the knees reach 90 degrees, then press.",
    cues: ["Don't let the lower back round", "Never fully lock the knees"],
  },
  {
    id: "bulgarian-split",
    name: "Bulgarian Split Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "squat",
    compound: true,
    instructions: "Rear foot elevated, lower the back knee toward the floor.",
    cues: ["Front shin near vertical for quads", "Drive through the whole foot"],
  },
  {
    id: "smith-squat",
    name: "Smith Machine Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["smith"],
    movement_pattern: "squat",
    compound: true,
    instructions: "Feet slightly forward, squat under the fixed bar path.",
    cues: ["Controlled 3s descent", "Stay mid-foot loaded"],
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    primary_muscle: "Quads",
    secondary_muscles: [],
    muscle_targets: ["Quads"],
    equipment_required: ["leg_developer"],
    movement_pattern: "squat",
    compound: false,
    instructions: "Extend the knees to full lockout, squeeze, lower slowly.",
    cues: ["Pause 1s at the top", "Toes slightly up"],
  },
  {
    id: "rdl",
    name: "Barbell Romanian Deadlift",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes", "Back"],
    muscle_targets: ["Hamstrings", "Glutes", "Lower Back"],
    equipment_required: ["barbell"],
    movement_pattern: "hinge",
    compound: true,
    instructions: "Push the hips back with a flat back until you feel a hamstring stretch.",
    cues: ["Bar stays against the legs", "Soft knees, not bent"],
  },
  {
    id: "db-rdl",
    name: "Dumbbell Romanian Deadlift",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Hamstrings", "Glutes"],
    equipment_required: ["dumbbell"],
    movement_pattern: "hinge",
    compound: true,
    instructions: "Hinge at the hips lowering the dumbbells along the thighs.",
    cues: ["Lats tight, chest proud", "Hips drive the movement"],
  },
  {
    id: "leg-curl",
    name: "Seated Leg Curl",
    primary_muscle: "Hamstrings",
    secondary_muscles: [],
    muscle_targets: ["Hamstrings"],
    equipment_required: ["leg_developer"],
    movement_pattern: "hinge",
    compound: false,
    instructions: "Curl the pad down under the calves and control the return.",
    cues: ["Hips stay down on the seat", "3s eccentric"],
  },
  {
    id: "kb-swing",
    name: "Kettlebell Swing",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings", "Core"],
    muscle_targets: ["Glutes", "Hamstrings"],
    equipment_required: ["kettlebell"],
    movement_pattern: "hinge",
    compound: true,
    instructions: "Hike the bell back and snap the hips to float it to chest height.",
    cues: ["It's a hinge, not a squat", "Lock out glutes at the top"],
  },
  {
    id: "hip-thrust",
    name: "Barbell Hip Thrust",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings"],
    muscle_targets: ["Glutes", "Hamstrings"],
    equipment_required: ["barbell", "bench"],
    movement_pattern: "hinge",
    compound: true,
    instructions: "Drive the hips to full extension with the shoulders on a bench.",
    cues: ["Tuck the chin, ribs down", "Pause 2s at lockout"],
  },
  {
    id: "glute-bridge",
    name: "Bodyweight Glute Bridge",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings"],
    muscle_targets: ["Glutes", "Hamstrings"],
    equipment_required: ["bodyweight"],
    movement_pattern: "hinge",
    compound: false,
    instructions: "Bridge the hips up squeezing the glutes hard at the top.",
    cues: ["Posterior tilt at the top", "Push through the heels"],
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Abs"],
    equipment_required: ["cable_high"],
    movement_pattern: "core",
    compound: false,
    instructions: "Kneel and crunch the ribcage toward the pelvis.",
    cues: ["Round the spine, don't hip hinge", "Exhale hard at the bottom"],
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Abs"],
    equipment_required: ["pullup_bar"],
    movement_pattern: "core",
    compound: false,
    instructions: "Raise the legs to hip height without swinging.",
    cues: ["Posteriorly tilt the pelvis", "No momentum"],
  },
  {
    id: "plank",
    name: "Plank",
    primary_muscle: "Core",
    secondary_muscles: ["Shoulders"],
    muscle_targets: ["Abs"],
    equipment_required: ["bodyweight"],
    movement_pattern: "core",
    compound: false,
    instructions: "Hold a rigid line from head to heels on the forearms.",
    cues: ["Squeeze glutes and quads", "Breathe shallow but steady"],
  },
  {
    id: "farmer-carry",
    name: "Farmer's Carry",
    primary_muscle: "Core",
    secondary_muscles: ["Back", "Arms"],
    muscle_targets: ["Abs", "Traps", "Forearms"],
    equipment_required: ["dumbbell"],
    movement_pattern: "carry",
    compound: true,
    instructions: "Walk tall with heavy dumbbells at the sides.",
    cues: ["Shoulders back and down", "Short, quick steps"],
  },
  {
    id: "standing-calf",
    name: "Standing Calf Raise",
    primary_muscle: "Calves",
    secondary_muscles: [],
    muscle_targets: ["Calves"],
    equipment_required: ["machine"],
    movement_pattern: "push",
    compound: false,
    instructions: "Rise onto the toes and lower into a deep stretch.",
    cues: ["2s pause in the stretch", "Full extension at the top"],
  },
  {
    id: "db-calf",
    name: "Dumbbell Calf Raise",
    primary_muscle: "Calves",
    secondary_muscles: [],
    muscle_targets: ["Calves"],
    equipment_required: ["dumbbell"],
    movement_pattern: "push",
    compound: false,
    instructions: "Hold dumbbells and raise onto the balls of the feet.",
    cues: ["Slow tempo, no bouncing", "Stand tall"],
  },
  {
    id: "smith-incline-press",
    name: "Smith Machine Incline Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Shoulders", "Arms"],
    muscle_targets: ["Upper Chest", "Front Delts", "Triceps"],
    equipment_required: ["smith", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions: "Bench at 30 degrees under the guided bar, press from upper chest to lockout.",
    cues: ["Set the bench so the bar lands on the collarbone line", "Controlled 2s eccentric"],
  },
  {
    id: "smith-flat-press",
    name: "Smith Machine Flat Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Shoulders", "Arms"],
    muscle_targets: ["Mid Chest", "Triceps", "Front Delts"],
    equipment_required: ["smith", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions: "Press the guided bar from mid-chest with feet planted and shoulder blades set.",
    cues: ["Elbows at 45 degrees", "Touch the shirt, don't bounce"],
  },
  {
    id: "smith-rdl",
    name: "Smith Machine Romanian Deadlift",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes", "Back"],
    muscle_targets: ["Hamstrings", "Glutes", "Lower Back"],
    equipment_required: ["smith"],
    movement_pattern: "hinge",
    compound: true,
    instructions: "Hinge the hips back sliding the guided bar down the thighs.",
    cues: ["Weight in the mid-foot", "Stop where the hamstrings stop stretching"],
  },
  {
    id: "smith-hip-thrust",
    name: "Smith Machine Hip Thrust",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings"],
    muscle_targets: ["Glutes", "Hamstrings"],
    equipment_required: ["smith", "bench"],
    movement_pattern: "hinge",
    compound: true,
    instructions: "Shoulders on the bench, drive the guided bar up to full hip extension.",
    cues: ["Chin tucked, ribs down", "2s squeeze at lockout"],
  },
  {
    id: "smith-shoulder-press",
    name: "Smith Machine Shoulder Press",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Front Delts", "Side Delts", "Triceps"],
    equipment_required: ["smith", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions: "Seated upright, press the guided bar from chin height to overhead.",
    cues: ["No excessive back arch", "Full lockout every rep"],
  },
  {
    id: "cable-straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    primary_muscle: "Back",
    secondary_muscles: ["Core"],
    muscle_targets: ["Lats"],
    equipment_required: ["cable_high"],
    movement_pattern: "pull",
    compound: false,
    instructions: "With near-straight arms, pull the bar from overhead to the thighs.",
    cues: ["Hinge slightly and stay there", "Feel the lats, not the triceps"],
  },
  {
    id: "rope-pushdown",
    name: "Rope Triceps Pushdown",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Triceps"],
    equipment_required: ["cable_high"],
    movement_pattern: "push",
    compound: false,
    instructions: "Push the rope down and spread the ends at the bottom.",
    cues: ["Upper arms glued to the ribs", "Squeeze 1s at lockout"],
  },
  {
    id: "leg-developer-extension",
    name: "Lever Leg Extension",
    primary_muscle: "Quads",
    secondary_muscles: [],
    muscle_targets: ["Quads"],
    equipment_required: ["leg_developer"],
    movement_pattern: "squat",
    compound: false,
    instructions: "Seated on the leg developer, extend the knees to lockout and lower slowly.",
    cues: ["Pause 1s at the top", "3s negative"],
  },
  {
    id: "lying-leg-curl",
    name: "Lying Leg Curl",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Calves"],
    muscle_targets: ["Hamstrings", "Calves"],
    equipment_required: ["leg_developer"],
    movement_pattern: "hinge",
    compound: false,
    instructions: "Face down, curl the pad toward the glutes and lower under control.",
    cues: ["Hips pressed into the pad", "Point the toes to bias the hamstrings"],
  },
  {
    id: "incline-db-flye",
    name: "Incline Dumbbell Flye",
    primary_muscle: "Chest",
    secondary_muscles: ["Shoulders"],
    muscle_targets: ["Upper Chest"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "push",
    compound: false,
    instructions: "On a 30 degree bench, open the arms wide in an arc and hug back up.",
    cues: ["Fixed soft elbow angle", "Stretch, don't drop"],
  },
  {
    id: "decline-pushup",
    name: "Decline Push-Up",
    primary_muscle: "Chest",
    secondary_muscles: ["Shoulders", "Core"],
    muscle_targets: ["Upper Chest", "Front Delts", "Triceps"],
    equipment_required: ["bodyweight", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions: "Feet on the bench, lower the chest to the floor in a straight line.",
    cues: ["Glutes tight, ribs down", "Elbows at 45 degrees"],
  },
  {
    id: "incline-db-row",
    name: "Incline Dumbbell Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Traps", "Biceps"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "pull",
    compound: true,
    instructions: "Chest supported on an incline bench, row both dumbbells to the ribs.",
    cues: ["No torso movement", "Pause 1s at the top"],
  },
  {
    id: "db-floor-press",
    name: "Dumbbell Floor Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms", "Shoulders"],
    muscle_targets: ["Mid Chest", "Triceps"],
    equipment_required: ["dumbbell"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Lie on the floor and press the dumbbells to lockout, letting the triceps touch down each rep.",
    cues: ["Pause when the elbows meet the floor", "Keep the wrists stacked over the elbows"],
  },
  {
    id: "incline-pushup",
    name: "Incline Push-Up",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms", "Core"],
    muscle_targets: ["Lower Chest", "Triceps", "Front Delts"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Hands on a raised surface, lower the chest to the edge keeping a straight body line.",
    cues: [
      "The higher the hands, the easier the rep",
      "Squeeze the glutes to stop the hips sagging",
    ],
  },
  {
    id: "archer-pushup",
    name: "Archer Push-Up",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms", "Core"],
    muscle_targets: ["Mid Chest", "Triceps"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Shift most of the weight onto one arm while the other stays straight out to the side.",
    cues: ["Lower toward the working hand", "Keep the straight arm lightly loaded for balance"],
  },
  {
    id: "db-pullover",
    name: "Dumbbell Pullover",
    primary_muscle: "Chest",
    secondary_muscles: ["Back"],
    muscle_targets: ["Lower Chest", "Lats"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Lie across a bench and lower one dumbbell in an arc behind the head, then pull it back over the chest.",
    cues: ["Keep a fixed soft elbow bend", "Stop at a deep stretch, don't overreach"],
  },
  {
    id: "band-chest-press",
    name: "Band Chest Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms", "Shoulders"],
    muscle_targets: ["Mid Chest", "Triceps", "Front Delts"],
    equipment_required: ["bands"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Anchor the band behind you at chest height and press the handles forward until the arms lock.",
    cues: [
      "Step out until there is tension at the start",
      "Bring the hands together at full reach",
    ],
  },
  {
    id: "chinup",
    name: "Chin-Up",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Biceps"],
    equipment_required: ["pullup_bar"],
    movement_pattern: "pull",
    compound: true,
    instructions:
      "With a shoulder-width underhand grip, pull the chin over the bar from a dead hang.",
    cues: ["Start from a full hang every rep", "Drive the elbows down and back"],
  },
  {
    id: "renegade-row",
    name: "Renegade Row",
    primary_muscle: "Back",
    secondary_muscles: ["Core", "Arms"],
    muscle_targets: ["Lats", "Traps", "Abs"],
    equipment_required: ["dumbbell"],
    movement_pattern: "pull",
    compound: true,
    instructions:
      "In a push-up position on the dumbbells, row one to the hip while bracing against rotation.",
    cues: ["Widen the feet for a stable base", "Keep the hips square to the floor"],
  },
  {
    id: "band-lat-pulldown",
    name: "Kneeling Band Pulldown",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Biceps"],
    equipment_required: ["bands"],
    movement_pattern: "pull",
    compound: true,
    instructions:
      "Anchor a band overhead, kneel back under tension and pull the handles to the collarbones.",
    cues: ["Lead with the elbows to the ribs", "Keep the chest tall, no leaning back"],
  },
  {
    id: "superman",
    name: "Superman Raise",
    primary_muscle: "Back",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Lower Back", "Glutes"],
    equipment_required: ["bodyweight"],
    movement_pattern: "hinge",
    compound: false,
    instructions:
      "Lie face down and lift the arms, chest and legs off the floor, holding briefly at the top.",
    cues: ["Reach long rather than high", "Pause 2s and lower under control"],
  },
  {
    id: "db-shrug",
    name: "Dumbbell Shrug",
    primary_muscle: "Back",
    secondary_muscles: [],
    muscle_targets: ["Traps"],
    equipment_required: ["dumbbell"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Hold heavy dumbbells at the sides and shrug the shoulders straight up toward the ears.",
    cues: ["Pause 1s at the top", "No rolling — straight up and down"],
  },
  {
    id: "pike-pushup",
    name: "Pike Push-Up",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Front Delts", "Triceps"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Hips high in an inverted V, lower the crown of the head toward the floor between the hands.",
    cues: ["Stack the shoulders over the hands", "Elevate the feet to add load"],
  },
  {
    id: "db-arnold-press",
    name: "Dumbbell Arnold Press",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Front Delts", "Side Delts", "Triceps"],
    equipment_required: ["dumbbell"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Start with palms facing you at chin height, rotate them out as you press overhead.",
    cues: ["Rotate and press as one smooth move", "Ribs down, no back arch"],
  },
  {
    id: "db-rear-delt-flye",
    name: "Bent-Over Reverse Flye",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Back"],
    muscle_targets: ["Rear Delts", "Traps"],
    equipment_required: ["dumbbell"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Hinge to near-parallel and raise light dumbbells out to the sides, leading with the elbows.",
    cues: [
      "Think about pulling the shoulder blades apart, then together",
      "No swinging or torso rise",
    ],
  },
  {
    id: "db-front-raise",
    name: "Dumbbell Front Raise",
    primary_muscle: "Shoulders",
    secondary_muscles: [],
    muscle_targets: ["Front Delts"],
    equipment_required: ["dumbbell"],
    movement_pattern: "push",
    compound: false,
    instructions: "Raise the dumbbells straight in front to shoulder height, then lower slowly.",
    cues: ["Stop at eye level", "No hip drive — keep it strict"],
  },
  {
    id: "db-upright-row",
    name: "Dumbbell Upright Row",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Arms", "Back"],
    muscle_targets: ["Side Delts", "Traps"],
    equipment_required: ["dumbbell"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Pull the dumbbells up the front of the body, leading with the elbows to just below the chin.",
    cues: ["Elbows stay higher than the wrists", "Stop if the shoulders pinch"],
  },
  {
    id: "band-lateral-raise",
    name: "Band Lateral Raise",
    primary_muscle: "Shoulders",
    secondary_muscles: [],
    muscle_targets: ["Side Delts"],
    equipment_required: ["bands"],
    movement_pattern: "push",
    compound: false,
    instructions: "Stand on the band and raise the handles out to the sides to shoulder height.",
    cues: ["Lead with the elbows", "Resist the band on the way down for 2s"],
  },
  {
    id: "band-overhead-press",
    name: "Band Overhead Press",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Arms", "Core"],
    muscle_targets: ["Front Delts", "Side Delts", "Triceps"],
    equipment_required: ["bands"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Stand on the band with the handles at the shoulders and press straight overhead to lockout.",
    cues: ["Squeeze the glutes, no back lean", "Finish with the hands over the ears"],
  },
  {
    id: "band-pull-apart",
    name: "Band Pull-Apart",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Back"],
    muscle_targets: ["Rear Delts", "Traps"],
    equipment_required: ["bands"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Hold the band at shoulder height with straight arms and stretch it to the chest, squeezing the mid-back.",
    cues: ["Keep the arms parallel to the floor", "Pause 1s with the band on the sternum"],
  },
  {
    id: "feet-elevated-pike-pushup",
    name: "Feet-Elevated Pike Push-Up",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Front Delts", "Triceps"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "With the feet on a raised surface and hips stacked high, lower the head between the hands and press back up.",
    cues: [
      "The more vertical the torso, the harder the rep",
      "Keep the elbows tracking forward, not flaring wide",
    ],
  },
  {
    id: "wall-handstand-hold",
    name: "Wall Handstand Hold",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Core", "Arms"],
    muscle_targets: ["Front Delts", "Side Delts"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Kick up to a handstand with the heels resting on a wall and hold a tall, locked position.",
    cues: [
      "Push the floor away to reach through the shoulders",
      "Squeeze the ribs and glutes so the back doesn't arch",
    ],
  },
  {
    id: "diamond-pushup",
    name: "Diamond Push-Up",
    primary_muscle: "Arms",
    secondary_muscles: ["Chest", "Shoulders"],
    muscle_targets: ["Triceps", "Mid Chest"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Hands together under the sternum forming a triangle, lower the chest to the hands.",
    cues: ["Keep the elbows brushing the ribs", "Straight line from head to heels"],
  },
  {
    id: "bench-dip",
    name: "Bench Dip",
    primary_muscle: "Arms",
    secondary_muscles: ["Chest", "Shoulders"],
    muscle_targets: ["Triceps", "Front Delts"],
    equipment_required: ["bodyweight", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Hands on the edge of a bench behind you, lower the hips until the elbows reach 90 degrees, then press up.",
    cues: ["Keep the back close to the bench", "Elevate the feet to make it harder"],
  },
  {
    id: "bar-triceps-extension",
    name: "Bar Triceps Extension",
    primary_muscle: "Arms",
    secondary_muscles: ["Chest"],
    muscle_targets: ["Triceps", "Mid Chest"],
    equipment_required: ["bodyweight", "pullup_bar"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Lean into a waist-high bar, let the head travel under it as the elbows bend, then extend the arms straight.",
    cues: ["Only the elbows move — keep the body rigid", "Step the feet back to add resistance"],
  },
  {
    id: "under-bar-curl",
    name: "Under-Bar Curl",
    primary_muscle: "Arms",
    secondary_muscles: ["Back"],
    muscle_targets: ["Biceps", "Lats", "Forearms"],
    equipment_required: ["bodyweight", "pullup_bar"],
    movement_pattern: "pull",
    compound: true,
    instructions:
      "Lie under a waist-high bar with an underhand grip and curl the forehead up to the bar, keeping the elbows fixed.",
    cues: [
      "Pin the upper arms in place so the elbows lead nothing",
      "Keep the hips up in a straight line",
    ],
  },
  {
    id: "db-hammer-curl",
    name: "Dumbbell Hammer Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps", "Forearms"],
    equipment_required: ["dumbbell"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Curl the dumbbells with a neutral (thumbs-up) grip held throughout.",
    cues: ["Elbows pinned to the ribs", "Lower for 2s every rep"],
  },
  {
    id: "db-overhead-triceps-ext",
    name: "Dumbbell Overhead Triceps Extension",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Triceps"],
    equipment_required: ["dumbbell"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Hold one dumbbell overhead with both hands and lower it behind the head, then extend to lockout.",
    cues: ["Keep the elbows pointing forward, not flaring", "Full stretch at the bottom"],
  },
  {
    id: "db-kickback",
    name: "Dumbbell Triceps Kickback",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Triceps"],
    equipment_required: ["dumbbell"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Hinge forward, pin the upper arm to the side and straighten the elbow behind you.",
    cues: ["Upper arm stays still — only the forearm moves", "Squeeze 1s at full lockout"],
  },
  {
    id: "band-curl",
    name: "Band Biceps Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps", "Forearms"],
    equipment_required: ["bands"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Stand on the band and curl the handles to the shoulders against the increasing tension.",
    cues: [
      "Keep the elbows fixed at the sides",
      "Control the return, don't let the band snap back",
    ],
  },
  {
    id: "band-pushdown",
    name: "Band Triceps Pushdown",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Triceps"],
    equipment_required: ["bands"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Anchor the band overhead and extend the elbows fully, keeping the upper arms locked to the ribs.",
    cues: ["Only the forearms move", "Spread the handles apart at lockout"],
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes", "Core"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["bodyweight"],
    movement_pattern: "squat",
    compound: true,
    instructions:
      "Sit down between the feet to at least parallel, keeping the heels planted, then stand tall.",
    cues: ["Knees track over the toes", "Chest up, arms forward as a counterbalance"],
  },
  {
    id: "split-squat",
    name: "Split Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["bodyweight"],
    movement_pattern: "squat",
    compound: true,
    instructions:
      "In a long stance, lower the back knee toward the floor and drive back up through the front foot.",
    cues: ["Front shin close to vertical", "Keep the torso upright"],
  },
  {
    id: "reverse-lunge",
    name: "Reverse Lunge",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes", "Core"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["bodyweight"],
    movement_pattern: "squat",
    compound: true,
    instructions: "Step one foot back and lower the knee to the floor, then push back to standing.",
    cues: [
      "Most of the weight stays on the front heel",
      "Step back far enough for a vertical front shin",
    ],
  },
  {
    id: "wall-sit",
    name: "Wall Sit",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads"],
    equipment_required: ["bodyweight"],
    movement_pattern: "squat",
    compound: false,
    instructions:
      "Slide down a wall until the thighs are parallel to the floor and hold the position.",
    cues: ["Knees stacked over the ankles", "Push the whole back flat into the wall"],
  },
  {
    id: "db-reverse-lunge",
    name: "Dumbbell Reverse Lunge",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["dumbbell"],
    movement_pattern: "squat",
    compound: true,
    instructions:
      "Holding dumbbells at the sides, step back into a lunge and return through the front leg.",
    cues: ["Torso stays tall", "Light touch of the back knee, no slam"],
  },
  {
    id: "db-walking-lunge",
    name: "Dumbbell Walking Lunge",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes", "Hamstrings"],
    muscle_targets: ["Quads", "Glutes", "Hamstrings"],
    equipment_required: ["dumbbell"],
    movement_pattern: "squat",
    compound: true,
    instructions:
      "Lunge forward alternating legs, walking across the room with dumbbells at the sides.",
    cues: ["Push through the front heel to stand", "Keep the steps in a straight line"],
  },
  {
    id: "db-step-up",
    name: "Dumbbell Step-Up",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "squat",
    compound: true,
    instructions:
      "Step onto a knee-height bench with one foot and stand fully before lowering under control.",
    cues: ["Drive through the top foot, don't push off the floor", "Control the way down for 2s"],
  },
  {
    id: "db-thruster",
    name: "Dumbbell Thruster",
    primary_muscle: "Quads",
    secondary_muscles: ["Shoulders", "Glutes"],
    muscle_targets: ["Quads", "Front Delts", "Glutes"],
    equipment_required: ["dumbbell"],
    movement_pattern: "squat",
    compound: true,
    instructions:
      "Front squat the dumbbells at the shoulders, then use the drive out of the hole to press them overhead.",
    cues: ["One continuous move from squat to press", "Finish tall with the hands over the ears"],
  },
  {
    id: "band-squat",
    name: "Band Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["bands"],
    movement_pattern: "squat",
    compound: true,
    instructions:
      "Stand on the band with the handles racked at the shoulders and squat to parallel against the tension.",
    cues: ["Tension peaks at the top — push the hips through", "Heels stay down throughout"],
  },
  {
    id: "nordic-curl",
    name: "Nordic Hamstring Curl",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes", "Calves"],
    muscle_targets: ["Hamstrings", "Glutes"],
    equipment_required: ["bodyweight"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "Kneel with the ankles anchored and lower the torso to the floor as slowly as possible, then pull back.",
    cues: [
      "Keep the hips extended in a straight line with the shoulders",
      "Catch with the hands and push off to assist",
    ],
  },
  {
    id: "single-leg-rdl",
    name: "Single-Leg Romanian Deadlift",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes", "Core"],
    muscle_targets: ["Hamstrings", "Glutes"],
    equipment_required: ["bodyweight"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "Balance on one leg and hinge the hips back, reaching the free leg straight behind you.",
    cues: [
      "Hips stay level — no opening to the side",
      "Feel the stretch in the standing hamstring",
    ],
  },
  {
    id: "db-single-leg-rdl",
    name: "Dumbbell Single-Leg RDL",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Hamstrings", "Glutes"],
    equipment_required: ["dumbbell"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "Hold a dumbbell in the opposite hand and hinge over the standing leg until the hamstring loads.",
    cues: ["Dumbbell tracks close to the shin", "Square the hips to the floor the whole way"],
  },
  {
    id: "band-good-morning",
    name: "Band Good Morning",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes", "Back"],
    muscle_targets: ["Hamstrings", "Glutes", "Lower Back"],
    equipment_required: ["bands"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "Loop the band under the feet and over the neck, then hinge the hips back with a flat back.",
    cues: ["Soft knees, not bent", "Push the hips back, not down"],
  },
  {
    id: "kb-rdl",
    name: "Kettlebell Romanian Deadlift",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes", "Back"],
    muscle_targets: ["Hamstrings", "Glutes", "Lower Back"],
    equipment_required: ["kettlebell"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "Hold the kettlebell at the hips and push them back, sliding the bell down the thighs to mid-shin.",
    cues: ["Lats tight to keep the bell close", "Stop where the hamstrings stop stretching"],
  },
  {
    id: "single-leg-glute-bridge",
    name: "Single-Leg Glute Bridge",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings"],
    muscle_targets: ["Glutes", "Hamstrings"],
    equipment_required: ["bodyweight"],
    movement_pattern: "hinge",
    compound: false,
    instructions:
      "Lying on your back with one foot planted, extend the other leg and bridge the hips up level.",
    cues: ["Keep the pelvis square, don't dip to one side", "Squeeze the glute hard at the top"],
  },
  {
    id: "bw-hip-thrust",
    name: "Bodyweight Hip Thrust",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings"],
    muscle_targets: ["Glutes", "Hamstrings"],
    equipment_required: ["bodyweight", "bench"],
    movement_pattern: "hinge",
    compound: true,
    instructions: "Upper back on a bench, drive the hips to full extension and pause at the top.",
    cues: ["Tuck the chin and keep the ribs down", "Shins vertical at lockout"],
  },
  {
    id: "db-hip-thrust",
    name: "Dumbbell Hip Thrust",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings"],
    muscle_targets: ["Glutes", "Hamstrings"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "Upper back on a bench with a dumbbell across the hips, drive to full hip extension.",
    cues: ["Cushion the dumbbell on the hip crease", "Pause 2s squeezing the glutes at the top"],
  },
  {
    id: "curtsy-lunge",
    name: "Curtsy Lunge",
    primary_muscle: "Glutes",
    secondary_muscles: ["Quads"],
    muscle_targets: ["Glutes", "Quads", "Abductors"],
    equipment_required: ["bodyweight"],
    movement_pattern: "squat",
    compound: true,
    instructions: "Step one leg diagonally behind the other and lower straight down, then return.",
    cues: ["Keep the front foot flat and stable", "Hips stay facing forward"],
  },
  {
    id: "db-sumo-deadlift",
    name: "Dumbbell Sumo Deadlift",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings", "Quads"],
    muscle_targets: ["Glutes", "Adductors", "Hamstrings"],
    equipment_required: ["dumbbell"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "Feet wide with toes out, hold a dumbbell between the legs and stand up by driving the hips forward.",
    cues: ["Knees track out over the toes", "Finish with a hard glute squeeze, not a lean back"],
  },
  {
    id: "kb-deadlift",
    name: "Kettlebell Deadlift",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings", "Back"],
    muscle_targets: ["Glutes", "Hamstrings", "Lower Back"],
    equipment_required: ["kettlebell"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "Kettlebell between the feet, hinge down to grip the handle and stand by pushing the floor away.",
    cues: ["Flat back, chest proud", "Hips and shoulders rise together"],
  },
  {
    id: "band-glute-kickback",
    name: "Band Glute Kickback",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings"],
    muscle_targets: ["Glutes", "Hamstrings"],
    equipment_required: ["bands"],
    movement_pattern: "hinge",
    compound: false,
    instructions:
      "Anchor the band low and around one ankle, then drive that leg straight back and squeeze.",
    cues: ["Keep the standing leg soft", "No arching the lower back to gain range"],
  },
  {
    id: "band-lateral-walk",
    name: "Band Lateral Walk",
    primary_muscle: "Glutes",
    secondary_muscles: ["Quads"],
    muscle_targets: ["Abductors", "Glutes"],
    equipment_required: ["bands"],
    movement_pattern: "carry",
    compound: false,
    instructions:
      "With a band around the knees or ankles, take controlled side steps keeping constant tension.",
    cues: ["Stay in a quarter-squat the whole set", "Toes point forward, don't waddle"],
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Abs"],
    equipment_required: ["bodyweight"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "On your back with arms and knees up, lower an opposite arm and leg while keeping the low back flat.",
    cues: ["Press the ribs down into the floor", "Move slowly and exhale as the limbs extend"],
  },
  {
    id: "bird-dog",
    name: "Bird Dog",
    primary_muscle: "Core",
    secondary_muscles: ["Glutes", "Back"],
    muscle_targets: ["Abs", "Lower Back", "Glutes"],
    equipment_required: ["bodyweight"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "From all fours, extend the opposite arm and leg to a straight line and hold, then switch.",
    cues: ["Keep the hips level with the floor", "Reach long, pause 2s"],
  },
  {
    id: "hollow-hold",
    name: "Hollow Body Hold",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Abs"],
    equipment_required: ["bodyweight"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "On your back, press the low back down and lift the shoulders and legs into a shallow banana shape.",
    cues: ["Lower the legs to raise the difficulty", "No gap between the low back and the floor"],
  },
  {
    id: "bicycle-crunch",
    name: "Bicycle Crunch",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Abs", "Obliques"],
    equipment_required: ["bodyweight"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "Alternate bringing each elbow toward the opposite knee while the other leg extends.",
    cues: ["Rotate from the ribs, not the arms", "Keep it slow — no frantic pedalling"],
  },
  {
    id: "side-plank",
    name: "Side Plank",
    primary_muscle: "Core",
    secondary_muscles: ["Shoulders", "Glutes"],
    muscle_targets: ["Obliques"],
    equipment_required: ["bodyweight"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "Stack the feet and prop up on one forearm, lifting the hips to a straight line and holding.",
    cues: [
      "Push the bottom shoulder away from the ear",
      "Squeeze the glutes to stop the hips dropping",
    ],
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Obliques", "Abs"],
    equipment_required: ["bodyweight"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "Sit with the heels off the floor and rotate the hands from hip to hip under control.",
    cues: ["Twist from the trunk, not just the arms", "Keep the chest tall, don't collapse"],
  },
  {
    id: "v-up",
    name: "V-Up",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Abs"],
    equipment_required: ["bodyweight"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "Lying flat, lift the straight legs and torso simultaneously to touch the hands to the feet.",
    cues: ["Reach past the shins", "Lower slowly — don't crash down"],
  },
  {
    id: "toes-to-bar",
    name: "Toes-to-Bar",
    primary_muscle: "Core",
    secondary_muscles: ["Back"],
    muscle_targets: ["Abs"],
    equipment_required: ["pullup_bar"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "Hang from the bar and raise the toes to touch it, controlling the swing on the way down.",
    cues: ["Start each rep from a still hang", "Regress to knee raises if the swing takes over"],
  },
  {
    id: "band-pallof-press",
    name: "Band Pallof Press",
    primary_muscle: "Core",
    secondary_muscles: ["Shoulders"],
    muscle_targets: ["Obliques", "Abs"],
    equipment_required: ["bands"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "Anchor the band at chest height to one side and press the handle straight out, resisting the pull to rotate.",
    cues: ["Squeeze the glutes and brace before pressing", "Hold 2s at full reach"],
  },
  {
    id: "bw-calf-raise",
    name: "Standing Calf Raise",
    primary_muscle: "Calves",
    secondary_muscles: [],
    muscle_targets: ["Calves"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Rise onto the toes as high as possible and lower into a full stretch, ideally off a step.",
    cues: ["2s pause in the bottom stretch", "Full, deliberate range every rep"],
  },
  {
    id: "single-leg-calf-raise",
    name: "Single-Leg Calf Raise",
    primary_muscle: "Calves",
    secondary_muscles: [],
    muscle_targets: ["Calves"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Balance on one foot on the edge of a step and raise and lower through the full range.",
    cues: ["Use a wall for balance only, not to push", "Control the drop — no bouncing"],
  },
  {
    id: "seated-db-calf-raise",
    name: "Seated Dumbbell Calf Raise",
    primary_muscle: "Calves",
    secondary_muscles: [],
    muscle_targets: ["Calves"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Sit with dumbbells resting on the knees and the balls of the feet on a raised edge, then raise the heels.",
    cues: ["Pause at the top and the stretched bottom", "Keep the reps slow and strict"],
  },
];
export const exerciseById = (id: string) => EXERCISES.find((e) => e.id === id);

/** Which muscle group each specific target belongs to. */
export const TARGET_MUSCLE_GROUP: Record<TargetMuscle, Muscle> = {
  "Upper Chest": "Chest",
  "Mid Chest": "Chest",
  "Lower Chest": "Chest",
  Lats: "Back",
  Traps: "Back",
  "Lower Back": "Back",
  "Front Delts": "Shoulders",
  "Side Delts": "Shoulders",
  "Rear Delts": "Shoulders",
  Biceps: "Arms",
  Triceps: "Arms",
  Forearms: "Arms",
  Quads: "Quads",
  Adductors: "Quads",
  Hamstrings: "Hamstrings",
  Glutes: "Glutes",
  Abductors: "Glutes",
  Abs: "Core",
  Obliques: "Core",
  Calves: "Calves",
};

/** Specific muscle targets, ordered by muscle group then top-to-bottom. */
export const TARGET_MUSCLES = Object.keys(TARGET_MUSCLE_GROUP) as TargetMuscle[];

/** Specific targets that belong to a muscle group. */
export const targetsForGroup = (group: Muscle): TargetMuscle[] =>
  TARGET_MUSCLES.filter((t) => TARGET_MUSCLE_GROUP[t] === group);

/** Fallback specific targets when a record predates the `muscle_targets` field. */
export const defaultMuscleTargets = (primary: Muscle): TargetMuscle[] => {
  const map: Record<Muscle, TargetMuscle[]> = {
    Chest: ["Mid Chest"],
    Back: ["Lats"],
    Shoulders: ["Side Delts"],
    Arms: ["Biceps"],
    Quads: ["Quads"],
    Hamstrings: ["Hamstrings"],
    Glutes: ["Glutes"],
    Core: ["Abs"],
    Calves: ["Calves"],
  };
  return map[primary];
};
