import type { Exercise } from "./types";

/**
 * The second half of the built-in exercise list (data.ts's EXERCISES holds
 * both), added so every exercise has several real alternatives — above all
 * for home gyms, where a swap used to offer one near-copy (barbell RDL →
 * dumbbell RDL). Same muscle doesn't mean same movement: each group now has
 * hinge and knee-flexion options for the hamstrings, presses and flyes for
 * the chest, and so on, in barbell, dumbbell, bench, Smith, high-cable,
 * leg-developer, kettlebell, band and bodyweight versions.
 *
 * Chosen from published comparisons rather than by feel (all confirmed
 * through web search results; journal sites are blocked here). The full
 * list is on Settings → Sources ("exerciseSelection"):
 * - Long muscle lengths: seated over prone leg curls (Maeo et al., Med Sci
 *   Sports Exerc 2021), overhead over pushdown triceps work (Maeo et al.,
 *   Eur J Sport Sci 2023), standing over seated calf raises (Kinoshita et
 *   al., Front Physiol 2023) — hence the incline curls, overhead
 *   extensions, deficit and long-lever options.
 * - Push-ups build as much as the bench press at matched effort (Kikuchi &
 *   Nakazato 2017; Calatayud et al., J Strength Cond Res 2015), so
 *   bodyweight presses are real alternatives, not fillers.
 * - Gluteus maximus: step-ups, then hip thrusts, split squats, deadlifts
 *   and lunges (Neto et al., J Sports Sci Med 2020, systematic review).
 * - Gluteus medius: side plank with hip abduction and side-lying hip
 *   abduction (Boren et al. 2011; Distefano et al., JOSPT 2009).
 * - Hamstrings: the Nordic curl leads hamstring EMG (Ebben 2009; McAllister
 *   et al. 2014), and hinges and knee-flexion curls work them differently
 *   (Stronger by Science's hamstring guide), so both kinds are listed.
 * - Quads: leg extensions grow the rectus femoris where squats grow the
 *   vasti (Zabaleta-Korta et al. 2021) — hence sissy squats and reverse
 *   Nordics at home.
 * - ACE-sponsored EMG studies: concentration curls (biceps), diamond
 *   push-ups, kickbacks and dips (triceps), the 45° incline row and seated
 *   rear lateral raise (rear delts), bent-forward cable crossovers and the
 *   pec deck (chest), bicycle crunches and the captain's chair (abs).
 *
 * `unilateral` marks one-side-at-a-time exercises, which the time model
 * counts for both sides (see generator.ts's estimateSeconds).
 */
export const EXERCISE_LIBRARY: Exercise[] = [
  /* ------------------------------- Chest ------------------------------- */
  {
    id: "bb-incline-bench",
    name: "Incline Barbell Bench Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Shoulders", "Arms"],
    muscle_targets: ["Upper Chest", "Front Delts", "Triceps"],
    equipment_required: ["barbell", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions: "Set the bench to 30 degrees and press the bar from the upper chest to lockout.",
    cues: ["Touch just below the collarbones", "Keep the shoulder blades pinned back"],
  },
  {
    id: "bb-floor-press",
    name: "Barbell Floor Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Mid Chest", "Triceps"],
    equipment_required: ["barbell"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Lie on the floor under the bar, lower until the upper arms touch the floor and press back up.",
    cues: ["Pause the elbows on the floor", "Elbows at about 45 degrees"],
  },
  {
    id: "db-decline-press",
    name: "Decline Dumbbell Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lower Chest", "Triceps"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "On a slight decline, press the dumbbells from the lower chest to lockout over the chest.",
    cues: ["Feet hooked securely", "Lower slowly to a deep stretch"],
  },
  {
    id: "db-squeeze-press",
    name: "Dumbbell Squeeze Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Mid Chest", "Triceps"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Press two dumbbells together over the chest and keep squeezing them against each other as you lower and press.",
    cues: ["Palms facing each other", "Never let the dumbbells drift apart"],
  },
  {
    id: "single-arm-db-bench",
    name: "Single-Arm Dumbbell Bench Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms", "Core"],
    muscle_targets: ["Mid Chest", "Triceps", "Obliques"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "push",
    compound: true,
    unilateral: true,
    instructions:
      "Press one dumbbell on a flat bench while bracing so the body doesn't roll toward the weight.",
    cues: ["Free hand on the bench or belly", "Hips stay level"],
  },
  {
    id: "deficit-pushup",
    name: "Deficit Push-up",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms", "Shoulders"],
    muscle_targets: ["Mid Chest", "Triceps", "Front Delts"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Do push-ups with the hands on two dumbbells, plates or books so the chest sinks below hand level.",
    cues: ["Lower into a deep stretch", "Body stays in one straight line"],
  },
  {
    id: "band-pushup",
    name: "Banded Push-up",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms", "Shoulders"],
    muscle_targets: ["Mid Chest", "Triceps", "Front Delts"],
    equipment_required: ["bodyweight", "bands"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Loop a band across the upper back, pin the ends under the hands and do push-ups against it.",
    cues: ["Band sits across the shoulder blades", "Full lockout at the top"],
  },
  {
    id: "chest-dip",
    name: "Chest Dip",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms", "Shoulders"],
    muscle_targets: ["Lower Chest", "Triceps", "Front Delts"],
    equipment_required: ["dip_bars"],
    movement_pattern: "push",
    compound: true,
    instructions: "Lean the torso forward on the dip bars and lower until the chest stretches.",
    cues: ["Chest over the hands", "Elbows flare slightly out"],
  },
  {
    id: "single-arm-high-cable-fly",
    name: "Single-Arm High Cable Fly",
    primary_muscle: "Chest",
    secondary_muscles: [],
    muscle_targets: ["Lower Chest", "Mid Chest"],
    equipment_required: ["cable_high"],
    movement_pattern: "push",
    compound: false,
    unilateral: true,
    instructions:
      "Stand side-on to the high pulley and sweep the handle down and across to the opposite hip.",
    cues: ["Soft bend in the elbow throughout", "Let the chest open fully at the start"],
  },
  {
    id: "cable-chest-press",
    name: "Standing Cable Chest Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms", "Shoulders"],
    muscle_targets: ["Mid Chest", "Triceps", "Front Delts"],
    equipment_required: ["cable"],
    movement_pattern: "push",
    compound: true,
    instructions: "In a split stance facing away from the pulleys, press both handles forward.",
    cues: ["Lean slightly forward", "Hands meet in front of the sternum"],
  },
  {
    id: "low-to-high-cable-fly",
    name: "Low-to-High Cable Fly",
    primary_muscle: "Chest",
    secondary_muscles: ["Shoulders"],
    muscle_targets: ["Upper Chest", "Front Delts"],
    equipment_required: ["cable"],
    movement_pattern: "push",
    compound: false,
    instructions: "With the pulleys low, sweep the handles up and together to chin height.",
    cues: ["Palms face up and in", "Lift with the chest, not the shoulders"],
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms", "Shoulders"],
    muscle_targets: ["Mid Chest", "Triceps", "Front Delts"],
    equipment_required: ["machine"],
    movement_pattern: "push",
    compound: true,
    instructions: "Set the handles at mid-chest height and press to just short of lockout.",
    cues: ["Back flat against the pad", "Control the return to a full stretch"],
  },
  {
    id: "pec-deck",
    name: "Pec Deck",
    primary_muscle: "Chest",
    secondary_muscles: [],
    muscle_targets: ["Mid Chest"],
    equipment_required: ["machine"],
    movement_pattern: "push",
    compound: false,
    instructions: "Bring the pads or handles together in front of the chest, then open slowly.",
    cues: ["Elbows slightly bent and fixed", "Squeeze for a second at the middle"],
  },
  {
    id: "kb-floor-press",
    name: "Kettlebell Floor Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Mid Chest", "Triceps"],
    equipment_required: ["kettlebell"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Lying on the floor, press the kettlebells up from the chest until the arms lock out.",
    cues: ["Bell rests on the back of the forearm", "Wrists straight"],
  },

  {
    id: "pseudo-planche-pushup",
    name: "Pseudo-Planche Push-up",
    primary_muscle: "Chest",
    secondary_muscles: ["Shoulders", "Arms"],
    muscle_targets: ["Mid Chest", "Front Delts", "Triceps"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Do push-ups with the hands turned out beside the lower ribs and the shoulders leaning forward past the hands.",
    cues: ["Lean forward before you lower", "Elbows tight to the body"],
  },
  {
    id: "decline-bench",
    name: "Decline Barbell Bench Press",
    primary_muscle: "Chest",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lower Chest", "Triceps"],
    equipment_required: ["barbell", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "On a decline bench with the feet hooked, lower the bar to the lower chest and press.",
    cues: ["Shoulder blades pinned", "Bar over the lower chest"],
  },
  /* -------------------------------- Back -------------------------------- */
  {
    id: "pendlay-row",
    name: "Pendlay Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms", "Shoulders"],
    muscle_targets: ["Lats", "Traps", "Rear Delts"],
    equipment_required: ["barbell"],
    movement_pattern: "pull",
    compound: true,
    instructions:
      "With the torso parallel to the floor, row the bar from the floor to the lower chest each rep.",
    cues: ["Reset the bar on the floor every rep", "Back flat, no torso swing"],
  },
  {
    id: "smith-row",
    name: "Smith Machine Bent-Over Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Traps", "Biceps"],
    equipment_required: ["smith"],
    movement_pattern: "pull",
    compound: true,
    instructions: "Hinge to about 45 degrees and row the Smith bar to the belly button.",
    cues: ["Elbows drive back past the torso", "Hold the hinge, don't stand up"],
  },
  {
    id: "smith-inverted-row",
    name: "Smith Machine Inverted Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Traps", "Biceps"],
    equipment_required: ["smith"],
    movement_pattern: "pull",
    compound: true,
    instructions:
      "Lock the Smith bar at hip height, hang underneath with straight legs and pull the chest to the bar.",
    cues: ["Body rigid like a plank", "Lower the bar to make it harder"],
  },
  {
    id: "db-bent-over-row",
    name: "Bent-Over Dumbbell Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Traps", "Biceps"],
    equipment_required: ["dumbbell"],
    movement_pattern: "pull",
    compound: true,
    instructions: "Hinge forward holding two dumbbells and row both to the hips.",
    cues: ["Palms facing each other", "Pull toward the back pockets"],
  },
  {
    id: "meadows-row",
    name: "Meadows Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms", "Shoulders"],
    muscle_targets: ["Lats", "Rear Delts", "Traps"],
    equipment_required: ["barbell"],
    movement_pattern: "pull",
    compound: true,
    unilateral: true,
    instructions:
      "Wedge one end of the bar in a corner, stand side-on to the loaded end and row it with one hand.",
    cues: ["Overhand grip on the sleeve", "Let the shoulder stretch at the bottom"],
  },
  {
    id: "landmine-t-bar-row",
    name: "Landmine T-Bar Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Traps", "Biceps"],
    equipment_required: ["barbell"],
    movement_pattern: "pull",
    compound: true,
    instructions:
      "Wedge one end of the bar in a corner, straddle it and row the loaded end with both hands just behind the plates.",
    cues: ["Chest up, back flat", "Squeeze the shoulder blades at the top"],
  },
  {
    id: "single-arm-lat-pulldown",
    name: "Half-Kneeling Single-Arm Lat Pulldown",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Biceps"],
    equipment_required: ["cable_high"],
    movement_pattern: "pull",
    compound: true,
    unilateral: true,
    instructions:
      "Kneel beside the high pulley and pull one handle down to the side of the chest, elbow to the hip.",
    cues: ["Reach up into a full stretch", "Elbow travels down and back"],
  },
  {
    id: "pullup-negative",
    name: "Pull-up Negative",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Biceps"],
    equipment_required: ["pullup_bar"],
    movement_pattern: "pull",
    compound: true,
    instructions:
      "Jump or step up to the top of a pull-up and lower yourself as slowly as you can to a dead hang.",
    cues: ["Take 3 to 5 seconds on the way down", "Shoulders stay down, away from the ears"],
  },
  {
    id: "kb-row",
    name: "Kettlebell Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Traps", "Biceps"],
    equipment_required: ["kettlebell"],
    movement_pattern: "pull",
    compound: true,
    unilateral: true,
    instructions: "In a staggered stance with one hand on the knee, row the kettlebell to the hip.",
    cues: ["Flat back", "Pull the elbow toward the back pocket"],
  },
  {
    id: "single-arm-cable-row",
    name: "Single-Arm Seated Cable Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Biceps"],
    equipment_required: ["cable"],
    movement_pattern: "pull",
    compound: true,
    unilateral: true,
    instructions: "Row one handle to the hip, letting the shoulder reach forward at the start.",
    cues: ["Torso stays square", "Finish with the elbow behind the body"],
  },
  {
    id: "machine-row",
    name: "Chest-Supported Machine Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms", "Shoulders"],
    muscle_targets: ["Lats", "Traps", "Rear Delts"],
    equipment_required: ["machine"],
    movement_pattern: "pull",
    compound: true,
    instructions: "Chest on the pad, row the handles back until the elbows pass the torso.",
    cues: ["Chest stays on the pad", "Pause one second at the back"],
  },
  {
    id: "band-straight-arm-pulldown",
    name: "Band Straight-Arm Pulldown",
    primary_muscle: "Back",
    secondary_muscles: [],
    muscle_targets: ["Lats"],
    equipment_required: ["bands"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Anchor a band high, and with straight arms sweep it down from overhead to the thighs.",
    cues: ["Slight hip hinge", "Arms stay straight"],
  },
  {
    id: "prone-y-raise",
    name: "Incline Prone Y-Raise",
    primary_muscle: "Back",
    secondary_muscles: ["Shoulders"],
    muscle_targets: ["Traps", "Rear Delts"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Lie face down on an incline bench and raise light dumbbells overhead in a Y with thumbs up.",
    cues: ["Lead with the thumbs", "Shoulder blades down and back"],
  },
  {
    id: "reverse-snow-angel",
    name: "Reverse Snow Angel",
    primary_muscle: "Back",
    secondary_muscles: ["Shoulders"],
    muscle_targets: ["Traps", "Rear Delts", "Lower Back"],
    equipment_required: ["bodyweight"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Lie face down with the chest just off the floor and sweep the arms from the hips to overhead and back.",
    cues: ["Hands hover off the floor", "Move slowly through the whole arc"],
  },
  {
    id: "bb-shrug",
    name: "Barbell Shrug",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Traps", "Forearms"],
    equipment_required: ["barbell"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Hold the bar at arm's length and shrug the shoulders straight up to the ears.",
    cues: ["No rolling the shoulders", "Pause at the top"],
  },

  {
    id: "back-extension",
    name: "45° Back Extension",
    primary_muscle: "Back",
    secondary_muscles: ["Glutes", "Hamstrings"],
    muscle_targets: ["Lower Back", "Glutes", "Hamstrings"],
    equipment_required: ["machine"],
    movement_pattern: "hinge",
    compound: false,
    instructions:
      "On a 45-degree hyperextension bench, lower the torso by hinging at the hips and rise until the body is straight.",
    cues: ["Pad just below the hip bones", "Don't overarch at the top"],
  },
  {
    id: "close-grip-lat-pulldown",
    name: "Close-Grip Lat Pulldown",
    primary_muscle: "Back",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Lats", "Biceps"],
    equipment_required: ["cable_high"],
    movement_pattern: "pull",
    compound: true,
    instructions:
      "With a close neutral grip (V-handle), pull to the upper chest, elbows down and back.",
    cues: ["Lean back slightly", "Full stretch at the top"],
  },
  {
    id: "t-bar-row-machine",
    name: "Chest-Supported T-Bar Row",
    primary_muscle: "Back",
    secondary_muscles: ["Arms", "Shoulders"],
    muscle_targets: ["Lats", "Traps", "Rear Delts"],
    equipment_required: ["machine"],
    movement_pattern: "pull",
    compound: true,
    instructions: "Chest on the pad of a T-bar row machine, row the handles to the lower chest.",
    cues: ["Chest stays on the pad", "Squeeze the shoulder blades"],
  },
  {
    id: "smith-shrug",
    name: "Smith Machine Shrug",
    primary_muscle: "Back",
    secondary_muscles: [],
    muscle_targets: ["Traps"],
    equipment_required: ["smith"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Hold the Smith bar at arm's length and shrug the shoulders straight up.",
    cues: ["Straight up, no rolling", "Pause at the top"],
  },
  /* ------------------------------ Shoulders ------------------------------ */
  {
    id: "landmine-press",
    name: "Landmine Press",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Chest", "Arms"],
    muscle_targets: ["Front Delts", "Upper Chest", "Triceps"],
    equipment_required: ["barbell"],
    movement_pattern: "push",
    compound: true,
    unilateral: true,
    instructions:
      "Wedge one end of the bar in a corner and press the loaded end up and forward with one hand.",
    cues: ["Staggered stance, ribs down", "Reach long at the top"],
  },
  {
    id: "bb-z-press",
    name: "Barbell Z-Press",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Arms", "Core"],
    muscle_targets: ["Front Delts", "Side Delts", "Triceps"],
    equipment_required: ["barbell"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Sit on the floor with legs straight and press the bar overhead from the front of the shoulders.",
    cues: ["Sit tall without leaning back", "Head through at lockout"],
  },
  {
    id: "kb-overhead-press",
    name: "Kettlebell Overhead Press",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Front Delts", "Side Delts", "Triceps"],
    equipment_required: ["kettlebell"],
    movement_pattern: "push",
    compound: true,
    unilateral: true,
    instructions: "From the rack position, press one kettlebell overhead to lockout.",
    cues: ["Squeeze the glutes", "Forearm vertical under the bell"],
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Front Delts", "Side Delts", "Triceps"],
    equipment_required: ["machine"],
    movement_pattern: "push",
    compound: true,
    instructions: "Press the handles overhead from shoulder height, back against the pad.",
    cues: ["Handles start at chin height", "Don't shrug at the top"],
  },
  {
    id: "seated-rear-lateral-raise",
    name: "Seated Rear Lateral Raise",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Back"],
    muscle_targets: ["Rear Delts", "Traps"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Sit on the end of a bench, chest toward the knees, and raise the dumbbells out to the sides.",
    cues: ["Pinkies lead the movement", "Keep the chest down on the thighs"],
  },
  {
    id: "chest-supported-rear-delt-row",
    name: "45° Incline Rear Delt Row",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Back", "Arms"],
    muscle_targets: ["Rear Delts", "Traps", "Lats"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "pull",
    compound: true,
    instructions:
      "Lie chest-down on a 45-degree bench and row the dumbbells with the elbows flared wide.",
    cues: ["Upper arms at 90 degrees to the body", "Pull the elbows high, not back"],
  },
  {
    id: "cable-rear-delt-fly",
    name: "Single-Arm Cable Rear Delt Fly",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Back"],
    muscle_targets: ["Rear Delts", "Traps"],
    equipment_required: ["cable_high"],
    movement_pattern: "pull",
    compound: false,
    unilateral: true,
    instructions:
      "Grab the high pulley cable with the opposite hand and sweep the arm back and out at shoulder height.",
    cues: ["Arm almost straight", "Stop when the hand is in line with the body"],
  },
  {
    id: "band-face-pull",
    name: "Band Face Pull",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Back"],
    muscle_targets: ["Rear Delts", "Traps"],
    equipment_required: ["bands"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Anchor a band at face height and pull it to the forehead, hands splitting apart.",
    cues: ["Thumbs point back at the end", "Elbows high"],
  },
  {
    id: "wall-handstand-pushup",
    name: "Wall Handstand Push-up",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Front Delts", "Triceps", "Side Delts"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Kick up into a handstand against a wall, lower the head to the floor and press back up.",
    cues: [
      "Hands a little wider than the shoulders",
      "Use feet-elevated pike push-ups until this is safe",
    ],
  },
  {
    id: "machine-lateral-raise",
    name: "Machine Lateral Raise",
    primary_muscle: "Shoulders",
    secondary_muscles: [],
    muscle_targets: ["Side Delts"],
    equipment_required: ["machine"],
    movement_pattern: "push",
    compound: false,
    instructions: "Raise the pads out to the sides to shoulder height, then lower slowly.",
    cues: ["Shoulders level with the pivot", "No shrugging"],
  },
  {
    id: "db-push-press",
    name: "Dumbbell Push Press",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Arms", "Quads"],
    muscle_targets: ["Front Delts", "Triceps", "Side Delts"],
    equipment_required: ["dumbbell"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Dip the knees slightly and drive the dumbbells overhead using the legs, then lower under control.",
    cues: ["Short, fast dip", "Lower slowly to the shoulders"],
  },

  {
    id: "reverse-pec-deck",
    name: "Reverse Pec Deck",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Back"],
    muscle_targets: ["Rear Delts", "Traps"],
    equipment_required: ["machine"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Facing the pec deck, sweep the handles back and out with nearly straight arms.",
    cues: ["Lead with the elbows", "Don't shrug"],
  },
  {
    id: "cable-upright-row",
    name: "Cable Upright Row",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Back"],
    muscle_targets: ["Side Delts", "Traps"],
    equipment_required: ["cable"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "From a low pulley, pull the bar or rope up along the body to chest height, elbows high.",
    cues: ["Elbows above the hands", "Stop at chest height"],
  },
  {
    id: "prone-t-raise",
    name: "Prone T-Raise",
    primary_muscle: "Shoulders",
    secondary_muscles: ["Back"],
    muscle_targets: ["Rear Delts", "Traps"],
    equipment_required: ["bodyweight"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Lie face down with arms out in a T and lift them off the floor, thumbs up.",
    cues: ["Squeeze the shoulder blades together", "Hold one second at the top"],
  },
  /* -------------------------------- Arms -------------------------------- */
  {
    id: "incline-db-curl",
    name: "Incline Dumbbell Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Sit back on a 45-degree incline bench with the arms hanging behind the body and curl both dumbbells.",
    cues: ["Elbows stay pointing down", "Full stretch at the bottom"],
  },
  {
    id: "concentration-curl",
    name: "Concentration Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "pull",
    compound: false,
    unilateral: true,
    instructions:
      "Sit on a bench with the elbow braced against the inner thigh and curl the dumbbell to the shoulder.",
    cues: ["Upper arm doesn't move", "Squeeze hard at the top"],
  },
  {
    id: "db-preacher-curl",
    name: "Dumbbell Preacher Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "pull",
    compound: false,
    unilateral: true,
    instructions:
      "Rest the back of the upper arm on the top of an incline bench's back pad and curl the dumbbell.",
    cues: ["Lower all the way to a straight arm", "Armpit tight to the pad"],
  },
  {
    id: "spider-curl",
    name: "Spider Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Lie chest-down on an incline bench with the arms hanging straight and curl the dumbbells up.",
    cues: ["Arms stay vertical", "Hard squeeze at the top"],
  },
  {
    id: "high-cable-curl",
    name: "Overhead Cable Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps"],
    equipment_required: ["cable_high"],
    movement_pattern: "pull",
    compound: false,
    unilateral: true,
    instructions:
      "Stand side-on to the high pulley with the arm out at shoulder height and curl the handle to the head.",
    cues: ["Upper arm stays level", "Control the way back"],
  },
  {
    id: "bayesian-curl",
    name: "Bayesian Cable Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps"],
    equipment_required: ["cable"],
    movement_pattern: "pull",
    compound: false,
    unilateral: true,
    instructions:
      "Face away from a low pulley so the arm is pulled behind the body, then curl the handle forward and up.",
    cues: ["Elbow stays slightly behind the torso", "Full stretch each rep"],
  },
  {
    id: "drag-curl",
    name: "Barbell Drag Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps", "Forearms"],
    equipment_required: ["barbell"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Curl the bar while dragging it up the torso, elbows travelling back.",
    cues: ["Bar stays in contact with the body", "Elbows go behind you"],
  },
  {
    id: "reverse-curl",
    name: "Barbell Reverse Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Forearms", "Biceps"],
    equipment_required: ["barbell"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Curl the bar with an overhand grip, palms facing down.",
    cues: ["Wrists straight", "Elbows pinned to the sides"],
  },
  {
    id: "zottman-curl",
    name: "Zottman Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps", "Forearms"],
    equipment_required: ["dumbbell"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Curl the dumbbells palms up, turn the palms down at the top and lower them slowly.",
    cues: ["Rotate only at the top", "Take three seconds on the way down"],
  },
  {
    id: "kb-curl",
    name: "Kettlebell Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps", "Forearms"],
    equipment_required: ["kettlebell"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Hold the kettlebell by the horns or handle and curl it to the chest.",
    cues: ["Elbows by the sides", "No swinging"],
  },
  {
    id: "close-grip-bench",
    name: "Close-Grip Bench Press",
    primary_muscle: "Arms",
    secondary_muscles: ["Chest", "Shoulders"],
    muscle_targets: ["Triceps", "Mid Chest", "Front Delts"],
    equipment_required: ["barbell", "bench"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Grip the bar shoulder-width apart and press, keeping the elbows close to the body.",
    cues: ["Hands just inside shoulder width", "Touch the lower chest"],
  },
  {
    id: "overhead-cable-extension",
    name: "Overhead Cable Triceps Extension",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Triceps"],
    equipment_required: ["cable_high"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Face away from the high pulley with the rope behind the head and extend the arms forward and up.",
    cues: ["Elbows stay next to the head", "Deep stretch behind the head"],
  },
  {
    id: "bb-lying-triceps-extension",
    name: "Barbell Lying Triceps Extension",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Triceps"],
    equipment_required: ["barbell", "bench"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Lying on a bench, lower the bar behind the head by bending only the elbows, then extend.",
    cues: ["Upper arms angled slightly back", "Elbows point at the ceiling"],
  },
  {
    id: "smith-bodyweight-triceps-extension",
    name: "Smith Machine Bodyweight Triceps Extension",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Triceps"],
    equipment_required: ["smith"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Lock the Smith bar at waist height, lean on it with straight arms and bend the elbows to bring the head under the bar.",
    cues: ["Body in one straight line", "Lower bar setting makes it harder"],
  },
  {
    id: "band-overhead-triceps-extension",
    name: "Band Overhead Triceps Extension",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Triceps"],
    equipment_required: ["bands"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Stand on a band or anchor it low behind you and extend the arms overhead from behind the head.",
    cues: ["Elbows point forward", "Full lockout overhead"],
  },
  {
    id: "db-wrist-curl",
    name: "Dumbbell Wrist Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Forearms"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Rest the forearms on a bench, palms up, and curl the dumbbells using only the wrists.",
    cues: ["Let the dumbbell roll to the fingers", "Forearms stay flat"],
  },
  {
    id: "db-reverse-wrist-curl",
    name: "Dumbbell Reverse Wrist Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Forearms"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "pull",
    compound: false,
    instructions:
      "Rest the forearms on a bench, palms down, and raise the backs of the hands toward you.",
    cues: ["Light weight", "Slow on the way down"],
  },
  {
    id: "close-grip-pushup",
    name: "Close-Grip Push-up",
    primary_muscle: "Arms",
    secondary_muscles: ["Chest", "Shoulders"],
    muscle_targets: ["Triceps", "Mid Chest", "Front Delts"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: true,
    instructions:
      "Do push-ups with the hands under the shoulders and the elbows brushing the ribs.",
    cues: ["Elbows point back, not out", "Lock out at the top"],
  },

  {
    id: "sphinx-pushup",
    name: "Sphinx Push-up",
    primary_muscle: "Arms",
    secondary_muscles: ["Chest"],
    muscle_targets: ["Triceps", "Mid Chest"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "From a plank on the forearms, press up onto the hands by straightening the elbows, then lower back to the forearms.",
    cues: ["Hands a little ahead of the shoulders", "Kneel to make it easier"],
  },
  {
    id: "cable-curl",
    name: "Cable Bicep Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps", "Forearms"],
    equipment_required: ["cable"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Curl a straight bar or EZ handle from a low pulley up to the chest.",
    cues: ["Elbows pinned to the sides", "Control the way down"],
  },
  {
    id: "machine-preacher-curl",
    name: "Machine Preacher Curl",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Biceps"],
    equipment_required: ["machine"],
    movement_pattern: "pull",
    compound: false,
    instructions: "Arms on the pad, curl the handles up and lower them to a full stretch.",
    cues: ["Armpits snug against the pad", "Straighten the arms fully"],
  },
  {
    id: "machine-triceps-extension",
    name: "Machine Triceps Extension",
    primary_muscle: "Arms",
    secondary_muscles: [],
    muscle_targets: ["Triceps"],
    equipment_required: ["machine"],
    movement_pattern: "push",
    compound: false,
    instructions: "Elbows on the pad, extend the handles down until the arms are straight.",
    cues: ["Elbows stay on the pad", "Squeeze at lockout"],
  },
  /* -------------------------------- Quads -------------------------------- */
  {
    id: "front-squat",
    name: "Barbell Front Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes", "Core"],
    muscle_targets: ["Quads", "Glutes", "Abs"],
    equipment_required: ["barbell"],
    movement_pattern: "squat",
    compound: true,
    instructions:
      "With the bar on the front of the shoulders, squat down between the heels and stand up.",
    cues: ["Elbows high", "Torso stays upright"],
  },
  {
    id: "db-front-squat",
    name: "Dumbbell Front Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["dumbbell"],
    movement_pattern: "squat",
    compound: true,
    instructions:
      "Rest a dumbbell on each shoulder and squat as deep as you can with a tall chest.",
    cues: ["Elbows forward", "Knees track over the toes"],
  },
  {
    id: "heel-elevated-goblet-squat",
    name: "Heel-Elevated Goblet Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["dumbbell"],
    movement_pattern: "squat",
    compound: true,
    instructions:
      "Stand with the heels on two plates or a wedge and squat with a dumbbell at the chest, knees well forward.",
    cues: ["Narrow stance", "Let the knees travel past the toes"],
  },
  {
    id: "smith-split-squat",
    name: "Smith Machine Split Squat",
    primary_muscle: "Glutes",
    secondary_muscles: ["Quads"],
    muscle_targets: ["Glutes", "Quads"],
    equipment_required: ["smith"],
    movement_pattern: "squat",
    compound: true,
    unilateral: true,
    instructions:
      "In a long split stance under the Smith bar, lower the back knee toward the floor and drive up.",
    cues: ["Front foot slightly ahead of the bar", "Push through the whole front foot"],
  },
  {
    id: "sissy-squat",
    name: "Sissy Squat",
    primary_muscle: "Quads",
    secondary_muscles: [],
    muscle_targets: ["Quads"],
    equipment_required: ["bodyweight"],
    movement_pattern: "squat",
    compound: false,
    instructions:
      "Hold a support, rise onto the toes and lean back as the knees travel forward and down, then return.",
    cues: [
      "Hips stay extended, body in a line from knee to head",
      "Go only as deep as the knees allow",
    ],
  },
  {
    id: "reverse-nordic",
    name: "Reverse Nordic",
    primary_muscle: "Quads",
    secondary_muscles: [],
    muscle_targets: ["Quads"],
    equipment_required: ["bodyweight"],
    movement_pattern: "squat",
    compound: false,
    instructions:
      "Kneel upright on a soft surface and lean back as far as you can control, keeping hips straight, then return.",
    cues: ["Squeeze the glutes the whole time", "Start with a small range"],
  },
  {
    id: "db-lateral-lunge",
    name: "Dumbbell Lateral Lunge",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Adductors", "Glutes"],
    equipment_required: ["dumbbell"],
    movement_pattern: "squat",
    compound: true,
    unilateral: true,
    instructions:
      "Step wide to one side, sit back into that hip with the other leg straight, and push back to the middle.",
    cues: ["Toes forward", "Chest up over the bent knee"],
  },
  {
    id: "cossack-squat",
    name: "Cossack Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Adductors", "Quads", "Glutes"],
    equipment_required: ["bodyweight"],
    movement_pattern: "squat",
    compound: true,
    unilateral: true,
    instructions:
      "From a very wide stance, squat down over one leg while the other stays straight with the toes up.",
    cues: ["Heel of the bent leg stays down", "Shift side to side under control"],
  },
  {
    id: "bb-reverse-lunge",
    name: "Barbell Reverse Lunge",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["barbell"],
    movement_pattern: "squat",
    compound: true,
    unilateral: true,
    instructions:
      "With the bar on the back, step back into a lunge and drive up through the front foot.",
    cues: ["Torso tall", "Back knee lightly touches the floor"],
  },
  {
    id: "hack-squat",
    name: "Machine Hack Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["machine"],
    movement_pattern: "squat",
    compound: true,
    instructions: "Shoulders under the pads, lower as deep as you can control and drive back up.",
    cues: ["Feet low on the platform for more quads", "Back flat against the pad"],
  },
  {
    id: "kb-goblet-squat",
    name: "Kettlebell Goblet Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["kettlebell"],
    movement_pattern: "squat",
    compound: true,
    instructions: "Hold a kettlebell by the horns at the chest and squat between the knees.",
    cues: ["Elbows inside the knees at the bottom", "Chest tall"],
  },
  {
    id: "smith-front-foot-elevated-split-squat",
    name: "Smith Machine Bulgarian Split Squat",
    primary_muscle: "Glutes",
    secondary_muscles: ["Quads"],
    muscle_targets: ["Glutes", "Quads"],
    equipment_required: ["smith", "bench"],
    movement_pattern: "squat",
    compound: true,
    unilateral: true,
    instructions:
      "Rear foot on a bench behind you and the Smith bar on the back, lower until the front thigh is parallel.",
    cues: ["Most of the weight on the front leg", "Control the bottom"],
  },
  {
    id: "copenhagen-adduction",
    name: "Copenhagen Adduction",
    primary_muscle: "Quads",
    secondary_muscles: ["Core"],
    muscle_targets: ["Adductors", "Obliques"],
    equipment_required: ["bodyweight", "bench"],
    movement_pattern: "core",
    compound: false,
    unilateral: true,
    instructions:
      "In a side plank with the top leg on a bench, lift the bottom leg to meet it and lower again.",
    cues: ["Bench under the knee is easier, under the ankle harder", "Hips stay high"],
  },
  {
    id: "machine-adduction",
    name: "Hip Adduction Machine",
    primary_muscle: "Quads",
    secondary_muscles: [],
    muscle_targets: ["Adductors"],
    equipment_required: ["machine"],
    movement_pattern: "squat",
    compound: false,
    instructions: "Squeeze the pads together from a wide start, then let them open slowly.",
    cues: ["Start as wide as is comfortable", "Pause when the pads meet"],
  },
  {
    id: "band-leg-extension",
    name: "Band Leg Extension",
    primary_muscle: "Quads",
    secondary_muscles: [],
    muscle_targets: ["Quads"],
    equipment_required: ["bands"],
    movement_pattern: "squat",
    compound: false,
    unilateral: true,
    instructions:
      "Sit on a chair with a band anchored low behind you around one ankle and straighten the knee.",
    cues: ["Thigh stays on the seat", "Squeeze at full extension"],
  },

  {
    id: "belt-squat",
    name: "Belt Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["machine"],
    movement_pattern: "squat",
    compound: true,
    instructions: "With the belt around the hips, squat down between the feet and stand up.",
    cues: ["Torso upright", "Knees track over the toes"],
  },
  {
    id: "pendulum-squat",
    name: "Pendulum Squat",
    primary_muscle: "Quads",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Quads", "Glutes"],
    equipment_required: ["machine"],
    movement_pattern: "squat",
    compound: true,
    instructions: "Shoulders under the pads, sink as deep as you can and drive back up.",
    cues: ["Feet mid-platform", "Full depth"],
  },
  /* ------------------------------ Hamstrings ------------------------------ */
  {
    id: "good-morning",
    name: "Barbell Good Morning",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes", "Back"],
    muscle_targets: ["Hamstrings", "Glutes", "Lower Back"],
    equipment_required: ["barbell"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "With the bar on the upper back and soft knees, push the hips back until the torso is near parallel.",
    cues: ["Back stays flat", "Light weight, slow stretch"],
  },
  {
    id: "db-lying-leg-curl",
    name: "Dumbbell Lying Leg Curl",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Calves"],
    muscle_targets: ["Hamstrings", "Calves"],
    equipment_required: ["dumbbell", "bench"],
    movement_pattern: "hinge",
    compound: false,
    instructions:
      "Lie face down on a bench with a dumbbell held between the feet and curl the heels toward the glutes.",
    cues: [
      "Have someone place the dumbbell, or squeeze it in from the floor",
      "Hips stay on the bench",
    ],
  },
  {
    id: "sliding-leg-curl",
    name: "Sliding Leg Curl",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Hamstrings", "Glutes"],
    equipment_required: ["bodyweight"],
    movement_pattern: "hinge",
    compound: false,
    instructions:
      "Lie on your back with the heels on a towel on a smooth floor, lift the hips and slide the heels in and out.",
    cues: ["Hips stay up the whole set", "Slide out slowly"],
  },
  {
    id: "hamstring-walkout",
    name: "Hamstring Walkout",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Hamstrings", "Glutes"],
    equipment_required: ["bodyweight"],
    movement_pattern: "hinge",
    compound: false,
    instructions:
      "From a glute bridge, walk the heels out in small steps until the legs are nearly straight, then walk back.",
    cues: ["Keep the hips lifted", "Small heel steps"],
  },
  {
    id: "elevated-hamstring-bridge",
    name: "Feet-Elevated Hamstring Bridge",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Hamstrings", "Glutes"],
    equipment_required: ["bodyweight", "bench"],
    movement_pattern: "hinge",
    compound: false,
    instructions:
      "Lie on your back with the heels on a bench and the knees only slightly bent, and drive the hips up.",
    cues: ["Push down through the heels", "Straighter legs work the hamstrings more"],
  },
  {
    id: "b-stance-rdl",
    name: "B-Stance Dumbbell RDL",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Hamstrings", "Glutes"],
    equipment_required: ["dumbbell"],
    movement_pattern: "hinge",
    compound: true,
    unilateral: true,
    instructions:
      "With one foot back on its toes as a kickstand, hinge over the front leg with dumbbells and stand back up.",
    cues: ["Most of the weight on the front leg", "Hips square"],
  },
  {
    id: "seated-leg-curl",
    name: "Machine Seated Leg Curl",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Calves"],
    muscle_targets: ["Hamstrings", "Calves"],
    equipment_required: ["machine"],
    movement_pattern: "hinge",
    compound: false,
    instructions: "Lean the torso forward on a seated leg curl and curl the pad under the seat.",
    cues: ["Lean forward for a deeper stretch", "Thigh pad snug"],
  },
  {
    id: "glute-ham-raise",
    name: "Glute-Ham Raise",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes", "Calves"],
    muscle_targets: ["Hamstrings", "Glutes", "Calves"],
    equipment_required: ["machine"],
    movement_pattern: "hinge",
    compound: false,
    instructions:
      "On a glute-ham developer, lower the torso forward from the knees and curl back up with the hamstrings.",
    cues: ["Hips stay straight", "Push the toes into the plate"],
  },
  {
    id: "band-leg-curl",
    name: "Band Lying Leg Curl",
    primary_muscle: "Hamstrings",
    secondary_muscles: [],
    muscle_targets: ["Hamstrings"],
    equipment_required: ["bands"],
    movement_pattern: "hinge",
    compound: false,
    instructions:
      "Lie face down with a band anchored low in front of you around the ankles and curl the heels toward the glutes.",
    cues: ["Hips pressed into the floor", "Slow on the way back"],
  },
  {
    id: "kb-single-leg-rdl",
    name: "Kettlebell Single-Leg RDL",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Hamstrings", "Glutes"],
    equipment_required: ["kettlebell"],
    movement_pattern: "hinge",
    compound: true,
    unilateral: true,
    instructions:
      "Holding a kettlebell in the opposite hand, hinge on one leg until the torso is near parallel and return.",
    cues: ["Back leg in line with the torso", "Hips stay level"],
  },
  {
    id: "smith-good-morning",
    name: "Smith Machine Good Morning",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes", "Back"],
    muscle_targets: ["Hamstrings", "Glutes", "Lower Back"],
    equipment_required: ["smith"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "With the Smith bar on the upper back, hinge at the hips with soft knees and return.",
    cues: ["Feet slightly in front of the bar", "Flat back"],
  },

  {
    id: "single-leg-sliding-leg-curl",
    name: "Single-Leg Sliding Leg Curl",
    primary_muscle: "Hamstrings",
    secondary_muscles: ["Glutes"],
    muscle_targets: ["Hamstrings", "Glutes"],
    equipment_required: ["bodyweight"],
    movement_pattern: "hinge",
    compound: false,
    unilateral: true,
    instructions:
      "Hips lifted with one heel on a towel on a smooth floor, slide that heel out and curl it back in.",
    cues: ["Free leg held up", "Once two legs is easy"],
  },
  /* -------------------------------- Glutes -------------------------------- */
  {
    id: "bb-deadlift",
    name: "Barbell Deadlift",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings", "Back", "Quads"],
    muscle_targets: ["Glutes", "Hamstrings", "Lower Back"],
    equipment_required: ["barbell"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "Grip the bar over the mid-foot, brace, and stand up by pushing the floor away until the hips lock out.",
    cues: ["Bar stays against the legs", "Chest and hips rise together"],
  },
  {
    id: "bb-sumo-deadlift",
    name: "Barbell Sumo Deadlift",
    primary_muscle: "Glutes",
    secondary_muscles: ["Quads", "Hamstrings"],
    muscle_targets: ["Glutes", "Adductors", "Hamstrings"],
    equipment_required: ["barbell"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "From a wide stance with the toes out, grip the bar inside the knees and stand up by spreading the floor.",
    cues: ["Knees track out over the toes", "Hips close to the bar"],
  },
  {
    id: "bw-step-up",
    name: "Step-Up",
    primary_muscle: "Glutes",
    secondary_muscles: ["Quads"],
    muscle_targets: ["Glutes", "Quads"],
    equipment_required: ["bodyweight", "bench"],
    movement_pattern: "squat",
    compound: true,
    unilateral: true,
    instructions:
      "Step one foot onto a bench and stand up on it, then lower slowly without pushing off the back foot.",
    cues: ["Lean the torso slightly forward", "Drive through the heel of the top foot"],
  },
  {
    id: "single-leg-hip-thrust",
    name: "Single-Leg Hip Thrust",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings"],
    muscle_targets: ["Glutes", "Hamstrings"],
    equipment_required: ["bodyweight", "bench"],
    movement_pattern: "hinge",
    compound: false,
    unilateral: true,
    instructions:
      "Upper back on a bench and one foot on the floor, drive the hips up until the body is flat.",
    cues: ["Chin tucked", "Pause at the top"],
  },
  {
    id: "deficit-reverse-lunge",
    name: "Deficit Reverse Lunge",
    primary_muscle: "Glutes",
    secondary_muscles: ["Quads"],
    muscle_targets: ["Glutes", "Quads"],
    equipment_required: ["dumbbell"],
    movement_pattern: "squat",
    compound: true,
    unilateral: true,
    instructions:
      "Stand on a low step or plate holding dumbbells and step back into a deep lunge, then drive back up.",
    cues: ["Slight forward lean", "Sink deep for the stretch"],
  },
  {
    id: "reverse-hyper-bench",
    name: "Bench Reverse Hyperextension",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings", "Back"],
    muscle_targets: ["Glutes", "Hamstrings", "Lower Back"],
    equipment_required: ["bodyweight", "bench"],
    movement_pattern: "hinge",
    compound: false,
    instructions:
      "Lie face down on a bench with the hips at the edge and raise the straight legs to body height.",
    cues: ["Hold the bench tight", "Squeeze the glutes at the top"],
  },
  {
    id: "frog-pump",
    name: "Frog Pump",
    primary_muscle: "Glutes",
    secondary_muscles: [],
    muscle_targets: ["Glutes", "Abductors"],
    equipment_required: ["bodyweight"],
    movement_pattern: "hinge",
    compound: false,
    instructions:
      "Lie on your back with the soles of the feet together and knees out, and drive the hips up.",
    cues: ["Heels close to the glutes", "Squeeze hard at the top"],
  },
  {
    id: "cable-pull-through",
    name: "Cable Pull-Through",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings"],
    muscle_targets: ["Glutes", "Hamstrings"],
    equipment_required: ["cable"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "Face away from a low pulley with the rope between the legs, hinge back and stand up by driving the hips forward.",
    cues: ["Arms just hold the rope", "Finish with the glutes, not the back"],
  },
  {
    id: "cable-kickback",
    name: "Cable Glute Kickback",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings"],
    muscle_targets: ["Glutes", "Hamstrings"],
    equipment_required: ["cable"],
    movement_pattern: "hinge",
    compound: false,
    unilateral: true,
    instructions: "With an ankle strap on a low pulley, lean forward and kick the leg back and up.",
    cues: ["Don't arch the lower back", "Hips stay square"],
  },
  {
    id: "side-plank-abduction",
    name: "Side Plank Hip Abduction",
    primary_muscle: "Glutes",
    secondary_muscles: ["Core"],
    muscle_targets: ["Abductors", "Obliques"],
    equipment_required: ["bodyweight"],
    movement_pattern: "core",
    compound: false,
    unilateral: true,
    instructions:
      "Hold a side plank and raise the top leg up and down without letting the hips drop.",
    cues: ["Body in one line", "Toes point forward"],
  },
  {
    id: "side-lying-hip-abduction",
    name: "Side-Lying Hip Abduction",
    primary_muscle: "Glutes",
    secondary_muscles: [],
    muscle_targets: ["Abductors"],
    equipment_required: ["bodyweight"],
    movement_pattern: "core",
    compound: false,
    unilateral: true,
    instructions:
      "Lying on your side, raise the straight top leg slightly behind the body and lower it.",
    cues: ["Heel leads, toes point forward", "Don't roll backward"],
  },
  {
    id: "band-clamshell",
    name: "Banded Clamshell",
    primary_muscle: "Glutes",
    secondary_muscles: [],
    muscle_targets: ["Abductors", "Glutes"],
    equipment_required: ["bands"],
    movement_pattern: "core",
    compound: false,
    unilateral: true,
    instructions:
      "Lying on your side with a band above the knees and the feet together, open the top knee.",
    cues: ["Feet stay touching", "Hips don't rock back"],
  },
  {
    id: "machine-abduction",
    name: "Hip Abduction Machine",
    primary_muscle: "Glutes",
    secondary_muscles: [],
    muscle_targets: ["Abductors", "Glutes"],
    equipment_required: ["machine"],
    movement_pattern: "core",
    compound: false,
    instructions: "Push the pads apart as far as you can, then return slowly.",
    cues: ["Lean slightly forward for more glute", "Pause at the widest point"],
  },
  {
    id: "cable-hip-abduction",
    name: "Cable Hip Abduction",
    primary_muscle: "Glutes",
    secondary_muscles: [],
    muscle_targets: ["Abductors"],
    equipment_required: ["cable"],
    movement_pattern: "core",
    compound: false,
    unilateral: true,
    instructions:
      "With an ankle strap on a low pulley, stand side-on and sweep the far leg out to the side.",
    cues: ["Torso upright", "Slow return across the body"],
  },
  {
    id: "kb-goblet-sumo-squat",
    name: "Kettlebell Sumo Squat",
    primary_muscle: "Glutes",
    secondary_muscles: ["Quads"],
    muscle_targets: ["Glutes", "Adductors", "Quads"],
    equipment_required: ["kettlebell"],
    movement_pattern: "squat",
    compound: true,
    instructions:
      "From a wide stance with the toes out, hold the kettlebell low and squat straight down between the legs.",
    cues: ["Knees push out", "Chest stays up"],
  },
  {
    id: "smith-reverse-lunge",
    name: "Smith Machine Reverse Lunge",
    primary_muscle: "Glutes",
    secondary_muscles: ["Quads"],
    muscle_targets: ["Glutes", "Quads"],
    equipment_required: ["smith"],
    movement_pattern: "squat",
    compound: true,
    unilateral: true,
    instructions:
      "With the Smith bar on the back, step one foot well back and lower the knee, then drive up.",
    cues: ["Long step for more glute", "Front shin slightly forward"],
  },

  {
    id: "machine-hip-thrust",
    name: "Machine Hip Thrust",
    primary_muscle: "Glutes",
    secondary_muscles: ["Hamstrings"],
    muscle_targets: ["Glutes", "Hamstrings"],
    equipment_required: ["machine"],
    movement_pattern: "hinge",
    compound: true,
    instructions:
      "Back against the pad and the belt over the hips, drive the hips up to full extension.",
    cues: ["Chin tucked", "Pause at the top"],
  },
  {
    id: "db-sumo-squat",
    name: "Dumbbell Sumo Squat",
    primary_muscle: "Glutes",
    secondary_muscles: ["Quads"],
    muscle_targets: ["Glutes", "Adductors", "Quads"],
    equipment_required: ["dumbbell"],
    movement_pattern: "squat",
    compound: true,
    instructions:
      "From a wide stance with the toes out, hold one dumbbell by the head between the legs and squat down.",
    cues: ["Knees push out", "Chest up"],
  },
  /* --------------------------------- Core --------------------------------- */
  {
    id: "crunch",
    name: "Crunch",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Abs"],
    equipment_required: ["bodyweight"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "Lying on your back with knees bent, curl the shoulders off the floor toward the hips.",
    cues: ["Lower back stays on the floor", "Breathe out as you curl"],
  },
  {
    id: "reverse-crunch",
    name: "Reverse Crunch",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Abs"],
    equipment_required: ["bodyweight"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "Lying on your back with knees bent, curl the hips off the floor toward the chest.",
    cues: ["Roll the pelvis, don't swing the legs", "Lower slowly"],
  },
  {
    id: "lying-leg-raise",
    name: "Lying Leg Raise",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Abs"],
    equipment_required: ["bodyweight"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "Lying flat, raise the straight legs to vertical and lower them without touching the floor.",
    cues: ["Press the lower back into the floor", "Bend the knees to make it easier"],
  },
  {
    id: "hanging-knee-raise",
    name: "Hanging Knee Raise",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Abs", "Obliques"],
    equipment_required: ["pullup_bar"],
    movement_pattern: "core",
    compound: false,
    instructions: "Hang from the bar and pull the knees up to the chest, curling the pelvis.",
    cues: ["No swinging", "Lower under control"],
  },
  {
    id: "decline-situp",
    name: "Decline Sit-up",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Abs"],
    equipment_required: ["bodyweight", "bench"],
    movement_pattern: "core",
    compound: false,
    instructions: "Feet hooked on a decline bench, lower back to just above flat and sit up.",
    cues: ["Curl up rather than yank", "Hold a plate to add load"],
  },
  {
    id: "barbell-rollout",
    name: "Barbell Rollout",
    primary_muscle: "Core",
    secondary_muscles: ["Back"],
    muscle_targets: ["Abs", "Lats"],
    equipment_required: ["barbell"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "Kneel behind a barbell with round plates and roll it forward as far as you can without the back sagging, then roll back.",
    cues: ["Ribs down, glutes tight", "Shorter range until it's controlled"],
  },
  {
    id: "suitcase-carry",
    name: "Suitcase Carry",
    primary_muscle: "Core",
    secondary_muscles: ["Arms"],
    muscle_targets: ["Obliques", "Forearms"],
    equipment_required: ["dumbbell"],
    movement_pattern: "carry",
    compound: true,
    unilateral: true,
    instructions: "Walk holding a heavy dumbbell in one hand without leaning toward it.",
    cues: ["Shoulders level", "Count steps or metres as reps"],
  },
  {
    id: "high-cable-woodchop",
    name: "High-to-Low Cable Woodchop",
    primary_muscle: "Core",
    secondary_muscles: ["Shoulders"],
    muscle_targets: ["Obliques", "Abs"],
    equipment_required: ["cable_high"],
    movement_pattern: "core",
    compound: false,
    unilateral: true,
    instructions:
      "Side-on to the high pulley, pull the handle down and across to the opposite knee, turning from the trunk.",
    cues: ["Arms stay fairly straight", "Pivot the back foot"],
  },
  {
    id: "landmine-rotation",
    name: "Landmine Rotation",
    primary_muscle: "Core",
    secondary_muscles: ["Shoulders"],
    muscle_targets: ["Obliques", "Abs"],
    equipment_required: ["barbell"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "Wedge one end of the bar in a corner, hold the other end overhead with straight arms and swing it hip to hip.",
    cues: ["Turn from the trunk, arms stay long", "Slow and controlled"],
  },
  {
    id: "dragon-flag",
    name: "Dragon Flag",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Abs"],
    equipment_required: ["bodyweight", "bench"],
    movement_pattern: "core",
    compound: false,
    instructions:
      "Lying on a bench and gripping behind your head, lift the body to vertical on the shoulders and lower it as one straight line.",
    cues: ["Only the shoulders touch the bench", "Bend the knees to make it easier"],
  },
  {
    id: "cable-pallof-press",
    name: "Cable Pallof Press",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Obliques", "Abs"],
    equipment_required: ["cable"],
    movement_pattern: "core",
    compound: false,
    unilateral: true,
    instructions:
      "Side-on to a pulley at chest height, press the handle straight out and resist being turned.",
    cues: ["Hips and shoulders face forward", "Pause two seconds at full reach"],
  },
  {
    id: "kb-windmill",
    name: "Kettlebell Windmill",
    primary_muscle: "Core",
    secondary_muscles: ["Shoulders", "Hamstrings"],
    muscle_targets: ["Obliques", "Hamstrings"],
    equipment_required: ["kettlebell"],
    movement_pattern: "core",
    compound: true,
    unilateral: true,
    instructions:
      "With a kettlebell locked out overhead, hinge sideways to touch the floor with the free hand and return.",
    cues: ["Eyes on the bell", "Arm stays vertical"],
  },
  {
    id: "db-side-bend",
    name: "Dumbbell Side Bend",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Obliques"],
    equipment_required: ["dumbbell"],
    movement_pattern: "core",
    compound: false,
    unilateral: true,
    instructions: "Holding one dumbbell, bend sideways toward it and come back up past upright.",
    cues: ["Move only sideways, not forward", "Slow stretch at the bottom"],
  },

  {
    id: "ab-crunch-machine",
    name: "Ab Crunch Machine",
    primary_muscle: "Core",
    secondary_muscles: [],
    muscle_targets: ["Abs"],
    equipment_required: ["machine"],
    movement_pattern: "core",
    compound: false,
    instructions: "Curl the torso down against the pads, bringing the ribs toward the hips.",
    cues: ["Round the spine, don't hinge", "Slow return"],
  },
  /* -------------------------------- Calves -------------------------------- */
  {
    id: "smith-calf-raise",
    name: "Smith Machine Calf Raise",
    primary_muscle: "Calves",
    secondary_muscles: [],
    muscle_targets: ["Calves"],
    equipment_required: ["smith"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "With the Smith bar on the back and the balls of the feet on a plate, lower the heels fully and rise high.",
    cues: ["Knees straight", "Pause in the stretch"],
  },
  {
    id: "single-leg-db-calf-raise",
    name: "Single-Leg Dumbbell Calf Raise",
    primary_muscle: "Calves",
    secondary_muscles: [],
    muscle_targets: ["Calves"],
    equipment_required: ["dumbbell"],
    movement_pattern: "push",
    compound: false,
    unilateral: true,
    instructions:
      "Stand on one foot on a step holding a dumbbell, lower the heel below the step and rise onto the toes.",
    cues: ["Hold something for balance", "Full stretch every rep"],
  },
  {
    id: "smith-seated-calf-raise",
    name: "Smith Machine Seated Calf Raise",
    primary_muscle: "Calves",
    secondary_muscles: [],
    muscle_targets: ["Calves"],
    equipment_required: ["smith", "bench"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Sit on a bench under the Smith bar padded on the knees, balls of the feet on a plate, and raise the heels.",
    cues: ["Knees bent 90 degrees", "Lower all the way down"],
  },
  {
    id: "leg-press-calf-raise",
    name: "Leg Press Calf Raise",
    primary_muscle: "Calves",
    secondary_muscles: [],
    muscle_targets: ["Calves"],
    equipment_required: ["leg_press"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "With the balls of the feet on the bottom edge of the platform and straight knees, push through the toes.",
    cues: ["Keep the safety handles in reach", "Full range of motion"],
  },
  {
    id: "seated-calf-machine",
    name: "Seated Calf Raise Machine",
    primary_muscle: "Calves",
    secondary_muscles: [],
    muscle_targets: ["Calves"],
    equipment_required: ["machine"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Pads on the thighs, lower the heels as far as possible and rise as high as possible.",
    cues: ["Pause at the bottom", "No bouncing"],
  },
  {
    id: "bent-knee-calf-raise",
    name: "Bent-Knee Calf Raise",
    primary_muscle: "Calves",
    secondary_muscles: [],
    muscle_targets: ["Calves"],
    equipment_required: ["bodyweight"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Stand on a step with the knees bent and kept bent, lower the heels and rise onto the toes.",
    cues: ["Knee angle stays the same", "Slow lowering"],
  },
  {
    id: "band-calf-raise",
    name: "Band Calf Press",
    primary_muscle: "Calves",
    secondary_muscles: [],
    muscle_targets: ["Calves"],
    equipment_required: ["bands"],
    movement_pattern: "push",
    compound: false,
    instructions:
      "Sitting with the legs straight and a band around the balls of the feet, point the toes against it.",
    cues: ["Hold the band ends tight", "Point fully, return slowly"],
  },
];
