/**
 * How popular each built-in exercise is, used to suggest familiar exercises
 * first (the generator, swaps, the Exercises list). Asked for after
 * suggestions included exercises the user had never heard of.
 *
 * No published ranking of exercise popularity exists (workout apps like
 * Hevy and Strong don't publish what their users log; checked through web
 * search results), so this is measured: the YouTube views, in millions, of
 * the top 20 search results for the exercise whose titles actually name it
 * (all of the exercise's main words, with synonyms such as RDL / Romanian
 * deadlift; "barbell" and "bodyweight" count as implied), searching both
 * the catalog name and its common name (e.g. "Tricep Pushdown") and taking
 * the higher. It measures how many people look an exercise up, not how
 * many do it, and it favours exercises with a well-known name. Measured on
 * 1 October 2026 with scripts/exercise-popularity (re-run it when
 * exercises are added; an exercise missing here counts as 0).
 *
 * DeltaBolic's channel (981 videos and Shorts, 2.2 billion views, scraped the same
 * day) was used to find popular exercises the list lacked — the cable
 * curl, machine preacher curl, reverse pec deck, dumbbell sumo squat,
 * decline bench press and others were added — and to drop niche ones.
 */
export const EXERCISE_POPULARITY: Record<string, number> = {
  pushup: 182.03,
  "seated-cable-row": 130.48,
  pullup: 119.47,
  "bb-bench": 116.07,
  plank: 87.95,
  "lateral-raise": 75.4,
  "bb-deadlift": 72.2,
  "bb-squat": 67.9,
  "lat-pulldown": 65.15,
  "bodyweight-squat": 62.15,
  "bulgarian-split": 50.2,
  "db-curl": 48.11,
  "face-pull": 47.94,
  rdl: 43.98,
  crunch: 42.88,
  "db-shoulder-press": 41.61,
  "leg-extension": 41.59,
  "leg-developer-extension": 41.59,
  "leg-press": 41.38,
  "bb-row": 39.6,
  "split-squat": 39.2,
  "db-row": 37.29,
  "cable-crossover": 34.79,
  "db-fly": 34.49,
  "bb-curl": 34.37,
  "db-hammer-curl": 32.95,
  "bw-step-up": 32.57,
  "lying-leg-raise": 31.71,
  "db-rear-delt-flye": 31.51,
  "russian-twist": 29.9,
  "db-overhead-triceps-ext": 29.04,
  chinup: 28.39,
  dips: 28.22,
  "wall-sit": 28.16,
  ohp: 27.76,
  "cable-lateral": 27.71,
  "glute-bridge": 27.49,
  skullcrusher: 26.29,
  "smith-incline-press": 25.04,
  "db-bench": 24.68,
  "cable-crunch": 24.59,
  "goblet-squat": 24.19,
  "incline-db-press": 24.01,
  "cable-pushdown": 23.41,
  "smith-flat-press": 23.09,
  "bb-incline-bench": 22.22,
  "pec-deck": 21.66,
  "concentration-curl": 20.64,
  "reverse-lunge": 20.23,
  "diamond-pushup": 18.76,
  "kb-swing": 18.71,
  "hip-thrust": 18.54,
  "pike-pushup": 18.34,
  "hanging-leg-raise": 18.23,
  "nordic-curl": 17.46,
  "machine-row": 17.06,
  "reverse-crunch": 16.97,
  "db-shrug": 16.51,
  "bw-calf-raise": 16.49,
  "leg-curl": 16.35,
  "seated-rear-lateral-raise": 16.18,
  "back-extension": 15.68,
  "bench-dip": 15.17,
  "rope-pushdown": 14.68,
  "single-arm-db-bench": 14.59,
  "chest-dip": 14.46,
  "landmine-t-bar-row": 14.17,
  "seated-leg-curl": 14.16,
  "machine-shoulder-press": 14.09,
  "smith-squat": 13.85,
  "dragon-flag": 13.26,
  "db-rdl": 12.67,
  "cable-straight-arm-pulldown": 12.28,
  "hack-squat": 11.92,
  "db-pullover": 11.57,
  "bicycle-crunch": 11.45,
  "incline-db-curl": 11.31,
  "cable-curl": 11.19,
  "single-arm-high-cable-fly": 11.04,
  "machine-chest-press": 11.01,
  "incline-db-row": 10.99,
  "db-kickback": 10.89,
  "side-plank": 10.84,
  "overhead-cable-extension": 10.63,
  "db-front-raise": 10.33,
  "bw-hip-thrust": 10.26,
  "db-bent-over-row": 9.93,
  "bb-sumo-deadlift": 9.93,
  "db-arnold-press": 9.7,
  "bb-lying-triceps-extension": 9.06,
  "front-squat": 8.88,
  "bird-dog": 8.56,
  "single-arm-cable-row": 8.34,
  "farmer-carry": 8.32,
  "machine-preacher-curl": 8.09,
  "reverse-pec-deck": 8.08,
  "cable-rear-delt-fly": 7.83,
  "v-up": 7.71,
  "standing-calf": 7.39,
  "decline-pushup": 6.83,
  "db-sumo-squat": 6.82,
  "smith-shoulder-press": 6.6,
  "incline-db-flye": 6.57,
  "cable-kickback": 6.07,
  "archer-pushup": 6.04,
  "db-floor-press": 5.86,
  "single-leg-rdl": 5.83,
  "spider-curl": 5.82,
  "sissy-squat": 5.7,
  "zottman-curl": 5.7,
  "decline-bench": 5.65,
  "low-to-high-cable-fly": 5.55,
  "single-arm-lat-pulldown": 5.5,
  "db-side-bend": 5.33,
  superman: 5.03,
  "good-morning": 4.75,
  "smith-rdl": 4.61,
  "db-calf": 4.58,
  "cable-pull-through": 4.57,
  "bayesian-curl": 4.56,
  "inverted-row": 4.45,
  "seated-calf-machine": 4.42,
  "incline-pushup": 4.41,
  "db-thruster": 4.25,
  "ab-crunch-machine": 4.07,
  "db-hip-thrust": 3.99,
  "db-upright-row": 3.99,
  "cossack-squat": 3.87,
  "machine-abduction": 3.81,
  "drag-curl": 3.77,
  "db-walking-lunge": 3.75,
  "single-leg-calf-raise": 3.74,
  "toes-to-bar": 3.62,
  "renegade-row": 3.51,
  "reverse-curl": 3.49,
  "belt-squat": 3.4,
  "db-push-press": 3.3,
  "db-front-squat": 2.91,
  "pendlay-row": 2.89,
  "bb-floor-press": 2.86,
  "close-grip-bench": 2.83,
  "machine-hip-thrust": 2.7,
  "machine-triceps-extension": 2.69,
  "db-step-up": 2.66,
  "kb-curl": 2.63,
  "single-leg-hip-thrust": 2.62,
  "cable-hip-abduction": 2.61,
  "db-decline-press": 2.6,
  "hollow-hold": 2.58,
  "dead-bug": 2.48,
  "kb-deadlift": 2.47,
  "pullup-negative": 2.43,
  "lying-leg-curl": 2.37,
  "frog-pump": 2.36,
  "bb-shrug": 2.35,
  "machine-lateral-raise": 2.29,
  "band-pull-apart": 2.21,
  "meadows-row": 2.12,
  "single-leg-glute-bridge": 2.07,
  "curtsy-lunge": 1.93,
  "smith-hip-thrust": 1.81,
  "pseudo-planche-pushup": 1.77,
  "reverse-snow-angel": 1.77,
  "kb-row": 1.75,
  "band-lateral-walk": 1.72,
  "decline-situp": 1.64,
  "kb-single-leg-rdl": 1.62,
  "glute-ham-raise": 1.56,
  "t-bar-row-machine": 1.53,
  "cable-upright-row": 1.53,
  "landmine-press": 1.53,
  "band-row": 1.5,
  "cable-pallof-press": 1.49,
  "close-grip-lat-pulldown": 1.46,
  "pendulum-squat": 1.44,
  "side-lying-hip-abduction": 1.44,
  "db-reverse-lunge": 1.4,
  "band-pushdown": 1.39,
  "db-lying-leg-curl": 1.38,
  "reverse-nordic": 1.33,
  "heel-elevated-goblet-squat": 1.33,
  "single-leg-db-calf-raise": 1.32,
  "db-sumo-deadlift": 1.31,
  "hanging-knee-raise": 1.3,
  "close-grip-pushup": 1.3,
  "band-leg-extension": 1.28,
  "kb-windmill": 1.28,
  "band-face-pull": 1.25,
  "barbell-rollout": 1.23,
  "db-wrist-curl": 1.22,
  "band-pallof-press": 1.2,
  "leg-press-calf-raise": 1.17,
  "kb-goblet-sumo-squat": 1.16,
  "band-lat-pulldown": 1.15,
  "cable-chest-press": 1.11,
  "band-squat": 1.06,
  "db-single-leg-rdl": 1.05,
  "deficit-reverse-lunge": 1.05,
  "bar-triceps-extension": 1.03,
  "kb-goblet-squat": 0.97,
  "db-reverse-wrist-curl": 0.96,
  "db-lateral-lunge": 0.95,
  "smith-row": 0.94,
  "smith-inverted-row": 0.94,
  "landmine-rotation": 0.91,
  "band-pushup": 0.9,
  "high-cable-woodchop": 0.87,
  "smith-shrug": 0.81,
  "bb-reverse-lunge": 0.8,
  "band-curl": 0.77,
  "band-lateral-raise": 0.77,
  "smith-good-morning": 0.75,
  "smith-front-foot-elevated-split-squat": 0.75,
  "kb-rdl": 0.74,
  "db-squeeze-press": 0.73,
  "deficit-pushup": 0.7,
  "band-chest-press": 0.69,
  "under-bar-curl": 0.67,
  "kb-floor-press": 0.64,
  "reverse-hyper-bench": 0.64,
  "smith-calf-raise": 0.63,
  "smith-split-squat": 0.62,
  "db-preacher-curl": 0.62,
  "seated-db-calf-raise": 0.6,
  "smith-reverse-lunge": 0.56,
  "suitcase-carry": 0.54,
  "band-good-morning": 0.52,
  "smith-bodyweight-triceps-extension": 0.51,
  "copenhagen-adduction": 0.48,
  "kb-overhead-press": 0.48,
  "band-fly": 0.46,
  "band-overhead-press": 0.46,
  "elevated-hamstring-bridge": 0.45,
  "prone-y-raise": 0.44,
  "hamstring-walkout": 0.44,
  "side-plank-abduction": 0.42,
  "wall-handstand-pushup": 0.42,
  "smith-seated-calf-raise": 0.4,
  "b-stance-rdl": 0.4,
  "band-clamshell": 0.39,
  "high-cable-curl": 0.39,
  "bent-knee-calf-raise": 0.38,
  "band-overhead-triceps-extension": 0.38,
  "bb-z-press": 0.38,
  "band-glute-kickback": 0.33,
  "sphinx-pushup": 0.27,
  "prone-t-raise": 0.23,
  "wall-handstand-hold": 0.21,
  "sliding-leg-curl": 0.2,
  "single-leg-sliding-leg-curl": 0.2,
  "band-straight-arm-pulldown": 0.19,
  "chest-supported-rear-delt-row": 0.17,
  "feet-elevated-pike-pushup": 0.06,
  "band-leg-curl": 0.03,
  "machine-adduction": 0.02,
  "band-calf-raise": 0.01,
};

/** Below 1 million views an exercise is "niche": suggested only when
 *  nothing better known fits (the app's own cut-off, not a published one:
 *  it splits the list into 199 familiar and 57 niche exercises). */
export const NICHE_BELOW_M = 1;

/** Millions of matched YouTube views (0 for your own exercises). */
export const popularityOf = (id: string) => EXERCISE_POPULARITY[id] ?? 0;

export const isNiche = (id: string) => popularityOf(id) < NICHE_BELOW_M;
